### ISSUE TITLE
[FR] an easy way to delete songs?

### ISSUE THREAD

**Issue by luuuciano** [vanilla-music/vanilla#103]
I really like the Vanilla minimalist way... but I need something to delete songs I do not like at all... so, delete the file (not just from the queue)...
There is no way to do that in Vanilla player?

**Comment by aminb** [comment]
OK so here's a PR for this: #126 

@adrian-bl good enough for merging?

**Comment by adrian-bl** [comment]
Hi,

Thanks a lot for the PR, looks fine to me.
But i made some changes to the code:

1: The code didn't check if getSong() returned NULL (this may happen if the queue is empty)
Fixed in: https://github.com/vanilla-music/vanilla/commit/84f153d49a838f3a86d8b3b8756945e5ec58c35d

2: We already had some deletion code in the LibraryActivity: I moved it to the PlaybackActivity in https://github.com/vanilla-music/vanilla/commit/2a6ce919f3d8b0a6d827123c9163d058f9343218, so now the context menu can use the same code :-)
-> https://github.com/vanilla-music/vanilla/commit/268c3b825c035924a8980c870dd493ce7b1e9703

This also has two nice side effects: It fixes a (rare) race condition where shiftCurrentSong() would race with deleteMedia() (the queue logic got sometimes messed up if (and only if) the song-to-be-deleted was also the NEXT song playing) and moves the whole deletion into a background thread and therefore avoids blocking the UI (well: not a big issue as deletions should be quick, but anyway :-) )

**Comment by aminb** [comment]
Hey, no worries.

That's awesome thanks for adiitional changes and tidying it up!

**Comment by luuuciano** [comment]
Just updated vanilla and I am using it a lot now!
It is amazing how it is improving the delete song task!
Thanks a lot

**Comment by aminb** [comment]
@luuuciano Glad you're enjoying it! Vanilla will get even better.
You're welcome ;)
