### ISSUE TITLE
App no longer in Play Store?

### ISSUE THREAD

**Issue by dseomn** [vanilla-music/vanilla#1113]
- Vanilla Music Version (Settings -> About): N/A
- Android Version: Android 11 / LineageOS 18.1
- Phone vendor / model: Motorola Moto G7 Plus / lake
- Application was downloaded from (use `[x]`): N/A
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [x] NA / Don't know.

## Description

I don't see the app in the Play Store app, and https://play.google.com/store/apps/details?id=ch.blinkenlights.android.vanilla (linked from https://vanilla-music.github.io/) says "We're sorry, the requested URL was not found on this server."

**Comment by adrian-bl** [comment]
Yea, turns out that i missed a policy change: Google didn't like the '(no ads, opensource)' anymore (?) in the title:

![image](https://user-images.githubusercontent.com/568734/140603336-9349deb6-6532-4855-8ff1-f10c1ac57d07.png)

I submitted an update in the playstore which is now in the review-pending state.

**Comment by adrian-bl** [comment]
Closing this since the app is back in the play store.
