### ISSUE TITLE
Embedded cover arts are not displayed for songs with <no album> tag (related to #819)

### ISSUE THREAD

**Issue by Alexey104** [vanilla-music/vanilla#1208]
- Vanilla Music Version (Settings -> About): 1.3.2 Released 10. Jan. 2024
- Android Version: 11 (LineageOS 18.1)
- Phone vendor / model: Redmi Note 5 Pro (Whyred)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [X] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [ ] No
  - [X] NA / Don't know.

## Description

Hello!
I saw #819, which has to be fixed according to the last post, but I still don't see cover arts for files having `no album` tag. I use `metaflac` and `mid3v2` tools on a desktop machine for tagging my flacs and mp3 respectively, and any desktop or Android music player can display embedded covers for those files without issues. Vanilla does also display them, but only if a file has a non-empty `album` tag. Otherwise, just the default picture is shown. Full rescan with flushing the database doesn't help.

I would appreciate any suggestions on how to solve this.

...

## Screenshot / Video (If applicable)

...
![Screenshot_20240604-234638_Vanilla_Music](https://github.com/vanilla-music/vanilla/assets/38672094/781485e5-167e-4bcf-bfc0-0f8c54a3146f)

**Comment by Denilseven** [comment]
Hey, thank you for pointing this out!   
I was starting to get hopeless on getting cover art to display in the app.

Adding something to the album tag (I'm using ``ffmpeg`` CLI, ``.m4a`` audio format) makes the cover show up normally everywhere (except for the file browser list, but that's by design I guess).

Files with the same album tag will use the same cover art as well, but that makes sense.

_p.s. I only went through the trouble of figuring this out 'cuz I like the app's interface that much hah_

**Comment by Alexey104** [comment]
> Files with the same album tag will use the same cover art as well

You can fix this by checking `Media library -> Group albums by folder`.
