### ISSUE TITLE
F-Droid?

### ISSUE THREAD

**Issue by mathstuf** [vanilla-music/vanilla#124]
Why not continue on with F-Droid and just ignore Google Play? (Just curious)

If you still don't want to continue, would you allow this issue to be used to figure out what to do next (where to fork, etc.)?

**Comment by adrian-bl** [comment]
LOL.. and we got removed again from the play store - with the same shady DMCA takedown notice:

This is a notification that your application, Vanilla Music, with package ID ch.blinkenlights.android.vanilla, has been removed from the Google Play Store.

REASON FOR REMOVAL: Alleged copyright infringement (according to the terms of the Digital Millenium Copyright Act).

All violations are tracked. Serious or repeated violations of any nature will result in the termination of your developer account, and investigation and possible termination of related Google accounts. If your account is terminated, payments will cease and Google may recover the proceeds of any past sales and the cost of any associated fees (such as chargebacks and payment transaction fees) from you.

Please review the Developer Distribution Agreement and Content Policy to ensure that your applications are compliant with our policies.

The DMCA is a United States copyright law that provides guidelines for online service provider liability in case of copyright infringement. Click here for more information about the DMCA, and see http://www.google.com/dmca.html for the process that Google requires in order to make a DMCA complaint.

Google may reinstate your application into the Google Play Store upon receipt of a counter notification pursuant to sections 512(g)(2) and (3) of the DMCA. Click here for more information about the requirements of a counter notification and a link to a sample counter notification. If you have legal questions about this notification, you should retain your own legal counsel.

Please note that we have included a text copy of the Infringement Notice we received for your reference.

The Google Play Team

Text copy of DMCA complaint: subject_lr_dmca: Your Request to Google 
full_name: christopher eby 
companyname: christopher eby 
represented_copyright_holder: christopher eby 
contact_email_noprefill: eby_christopher@yahoo.co.uk 
country_residence: US 
location_of_copyrighted_work: source code: 
https://github.com/kreed/vanilla/tree/master/src/org/kreed/vanilla 
description_of_copyrighted_work: Hi, 
The infringing applications are copys of my application. They stole my app 
code from GitHub. 
GitHub link: 
https://github.com/kreed/vanilla/tree/master/src/org/kreed/vanilla 

you can compare my application and source code with this infringing 
application. My application is over 2 years old (which you can verify) , 
while the infringing app was published only few days or months ago. The 
developer released my copyrighted project(vanilla mp3 player) in its 
entirety which is a clear violation of copyright laws. 
hidden_category: 
url_box: https://play.google.com/store/apps/details?id=com.music.playerpro 
url_box: https://play.google.com/store/apps/details?id=com.developer.music 
url_box: 
https://play.google.com/store/apps/details?id=com.gasunbun.musicplayer 
url_box: 
https://play.google.com/store/apps/details?id=com.technocuz.tessplayer 
url_box: https://play.google.com/store/apps/details?id=reproductor.musica 
url_box: 
https://play.google.com/store/apps/details?id=ch.blinkenlights.android.vanilla 
dmca_affirmations_authorized: agree 
dmca_affirmations_penalty: agree1 
signature: christopher eby 
hidden_product: googleplay 
hidden_ctx: 
geolocation: US 


:---- Automatically added fields ----: 
Language: en 
IIILanguage: en 
auto-helpcenter-id: 1647639 
auto-helpcenter-name: legal 
auto-internal-helpcenter-name: legal 
auto-full-url: 
https://support.google.com/legal/contact/lr_dmca?product=googleplay 
auto-user-logged-in: true 
auto-user-was-internal: false 
IssueType: lr_dmca 
form-id: lr_dmca 
form: lr_dmca 
subject-line-field-id: subject_lr_dmca 
body-text-field-id: 
AutoDetectedBrowser: Firefox 34.0 
AutoDetectedOS: Windows Windows NT 6.1

**Comment by mvdan** [comment]
Ugh, this is all very weird. Isn't the original app Apache2? You should be completely free to fork the app and publish it anywhere you'd like.

Saying that his repo was the original and that yours is a copy will not get your app removed from F-Droid for sure.

**Comment by adrian-bl** [comment]
The original version is MIT licensed.

Looks like google simply doesnt READ the takedown notice. They probably have some stupid bot that simply takes down apps.

**Comment by mvdan** [comment]
What weirds me out the most is that upstream is doing these takedown notices, when they explicitly released the app under a permissive free software license.

**Comment by aminb** [comment]
@dandv Can you tell us how in the world does this work at Google?

@adrian-bl I don't think putting the app on the store is worth all of this hassle. I'm considering pulling my apps off of there as well.

**Comment by mathstuf** [comment]
@mvdan it isn't upstream; the original author is from Texas or so and has his own website with email so a yahoo.co.UK address is very unlikely to be his. My guess is still that some asshat doesn't like that vanilla is better than their app and wants to take it down.

**Comment by adrian-bl** [comment]
The take-down notices do *not* come from Chris, aka 'Upstream':

Back in 2012, (after he marked Vanilla Music as 'abandoned'), i asked Chris if it was ok for him if i pick up the development & keep using the name. He was glad that someone picks up the project and gave me permission to do so.

I also contacted him after receiving the first impersonated takedown notice and he ensured to me that he has nothing to do with it. (And i have no reason to doubt this - what would he gain from it? And as others pointed out: Why would he use a yahoo.co.uk account when he has is own hosted-gmail domain?)

Another funny side note: 2 days ago, i received a (real!) e-mail from google. Quote:

" Given the quality and volume of downloads of your apps I have highlighted you as a developer with great potential of becoming our strategic partner.  "

Hmm.. i don't think this will happen - ever. ;-)
