### ISSUE TITLE
Press and Hold Next Track Fast Forwards Song 

### ISSUE THREAD

**Issue by Allanitomwesh** [vanilla-music/vanilla#141]
Vanilla Player has shuffle,previous track,play, next track and repeat buttons in the playback screen. It also has the previous,play,and next buttons in the notification bar.
It would be great if the previous and next buttons acted as fast forward and fast rewind buttons when you press and hold them. It is a very handy way to seek inside a track. Even better would be if this press and hold worked in the notification bar,allowing us to seek the track without actually opening the Vanilla Music app and using the track line. 
Version 0.9.41 from F-Droid

**Comment by aminb** [comment]
@Allanitomwesh AFAIK, we can't have `onLongClickListener` for notifications since they're `RemoteView`s. Here's [a related SO question](https://stackoverflow.com/questions/7003592/android-catch-events-on-notification-long-press).

So, the best we can do in terms of long press actions are in the playback screen itself. But is that really necessary? (Since we've already got a progress bar for seeking in the track, which I think is way easier than having to long press and release a button several times.)

Also, if you go to `Settings -> Notifications`, there's a `Notification Action` which lets you choose what happens when you tap on the notification, and one of the options is that to open a mini pop, which I think is nice. We might be able to add a seek bar in this popup, if that's something that would make sense? @adrian-bl

**Comment by Allanitomwesh** [comment]
Just tried the popup,and yeah that would work. Would it also be possible to add seeking to the volume buttons? Dunno how but it would be nice.

**Comment by aminb** [comment]
About the volume long press, I think it is possible to use them for seeking in the track when the screen is off, but usually ROMs already use that to go to prev/next track. I'm not sure if overriding that would work or it would conflict.

OK then, let's see what @adrian-bl thinks about these points :)

**Comment by adrian-bl** [comment]
Using the volume long press buttons for seeking is not possible:
An application running in the background can not capture such button events and the next-track-on-volume-long-press mechanism of custom ROMS simply works by sending a media-button event.
(And there will only be one event sent on longpress - you will not know at which point the user stopped pressing the button)

But seeking by long-press in the notification may be possible (we would have to give it a try: android > 4.4.4 does capture some long-press events in the notification area)

**Comment by Allanitomwesh** [comment]
That would be awesome,I prefer to set my notification to open the full app when I click it (hence why I never tried the popup before) and seeking a track from there would be winner. Give it your best shot.

**Comment by adrian-bl** [comment]
I had a look at androids framework code and, IMO - this is also not doable in the notification area.

I'm therefore closing this bug - if someone finds a way to capture long presses in the notification area: feel free to reopen the bug.

**Comment by n-o-o-b** [comment]
Is this not possible to implement inside the app? Would be useful, it's more fiddly to rewind a short distance using the seekbar.

**Comment by Adonai** [comment]
Possible, I did that once in my own fork.

**Comment by n-o-o-b** [comment]
> Possible, I did that once in my own fork.

Cool! Is it still active?

**Comment by Adonai** [comment]
@n-o-o-b , sorry, no, that was 7 years ago and silly me never streamlined his patches.

**Comment by n-o-o-b** [comment]
@Adonai OK.
@adrian-bl Provided this isn't hard to implement, it seems like a no-brainer to have it in the app. Coming from listening to music on iOS, I'm surprised that more Android apps don't have the feature.

**Comment by Allanitomwesh** [comment]
looking forward to it
