### ISSUE TITLE
Play/Pause as the shake action is useless

### ISSUE THREAD

**Issue by mathstuf** [vanilla-music/vanilla#15]
Since the accelerometer only triggers the action when music is playing, there is no way for the music to be resumed after pausing.

**Comment by adrian-bl** [comment]
finally fixed with: https://github.com/vanilla-music/vanilla/commit/3974138451229d871133840b1342ff69f2eec8f5

**Comment by mathstuf** [comment]
Thanks!

**Comment by un-logic** [comment]
As far as I understand patch mentioned above doesn't remove 'play' feature but instead it allows Vanilla to keep listening for sensor events even when paused, which is great! Can't wait to get my hands on next build. Thank you, adrian-bl!

**Comment by un-logic** [comment]
Well, it worked, but after playing around with it for quite a time I have to admit, that it is still nearly useless, this time due to relatively low upper limit of shakeaction threshold. Current maximum value is 15 (meters per square second?) which triggers action if you step a bit harder during walking or running. Maybe increasing this value to 30 (approximately 3g?) will do the job? This should be an easy fix.
TIA.

**Comment by adrian-bl** [comment]
I guess your device is very sensitive. But i changed the max value to 30:

https://github.com/vanilla-music/vanilla/commit/d910266b24d50b87c825c36faa69cba43440bcbf

hope this helps :)
