### ISSUE TITLE
Change repository into standalone

### ISSUE THREAD

**Issue by notfoss** [vanilla-music/vanilla#151]
Hi, when I try searching inside code of this repository github shows the following error:

> Sorry, forked repositories are not currently searchable.

> You could try searching the parent repository. 

Since the parent repo is no longer active and maintained, I believe this repository should be made into a standalone.

To do so, one of the admins for this project need to contact GitHub support and request them to do the same.

**Comment by aminb** [comment]
I agree with this, since many times I've found myself trying to do a quick search in the repo, but haven't been able to do so.

Kudos to @kreed for [the original] Vanilla, but I also think we've come somewhat a long way, and the project is not just a *fork*, IMHO.

What are your thoughts @adrian-bl?

P.S. Ofcourse if the repo is transferred to a normal repo, we can mention [kreed/vanilla](https://github.com/kreed/vanilla) in the README / about page.

**Comment by notfoss** [comment]
Well, it is a fork even if substantial changes have been added. Similar to how LibreOffice is a fork of OpenOffice or Pentadactyl is a fork of Vimperator.

The issue here is how GitHub treats forked repositories.

The best way to shed the fork weightage - if you are inclined to do so - would be to rename the project.

Alternatively, you can request @kreed to put a notice on his repository that official development is continuing at https://github.com/vanilla-music/vanilla. He has already put up an abandoned notice.

**Comment by adrian-bl** [comment]
I do not see a point in changing the status of the repository just to work around github bugs/features - and the github search is IMO abysmal anyway.

Cloning the repo and running 'ack' or 'grep' on it takes like 20 seconds.

**Comment by aminb** [comment]
@notfoss I do know we're technically still a fork, but I italicized *fork* to try convey that I intended it to mean the *restrictions github puts on forks*.

Since we're going to keep the name **Vanilla**, and Adrian's points are valid, I'm closing this as `wontfix`, but if there are any opinions/arguments feel free to leave a comment mentioning @adrian-bl or send him an email.

**Comment by notfoss** [comment]
@adrian-bl @aminb 

Well the best use of github's search is when I am not using my personal machine, or am using a mobile device or windows. In those cases cloning a copy locally is not possible. This is not so much about status as it is about usability.
