### ISSUE TITLE
Switching to/Supporting Android Studio

### ISSUE THREAD

**Issue by AltNico** [vanilla-music/vanilla#152]
Are there any plans to switch to or support Android Studio in the future?
Vanilla does not have to drop support for Eclipse but if you would add some gradle stuff, you would be able to use Android Studio to develop Vanilla. See [F-Droid](https://gitlab.com/fdroid/fdroidclient/tree/master), for an example.

I think, Vanilla will come to the point where it has to switch to Android Studio because it is the official Android IDE and ADT isn't support anymore.
I can help you with switching to AS, if wanted.

**Comment by aminb** [comment]
If I recall correctly, I, too, had mentioned this before, but basically switching to Android Studio and/or using Gradle would be beneficial if we were to use other libraries, but since the goal of Vanilla is to be minimal, the effort has been to avoid using external libraries.

Well, except for DragSortListView and ViewPagerIndicator, which were directly copied over into the project.

On the other hand, I think adding Android Studio support/structure might help attract newbie devs, since it's a one-click import in the Android Studio; and after all, it's the "recommended" way (by Google) of developing Android apps.

So, yeah I don't think it's necessary, but adding support wouldn't hurt and it should be pretty easy.

@adrian-bl ?

**Comment by adrian-bl** [comment]
The included versions of DragSortListview and ViewPagerIndicator have both been patched and are out-of-sync with upstream. But we could add https://github.com/adrian-bl/bastp as a dependency ;-)

I'm using nedit/geany to develop and therefore do not really care much about eclipse or other IDEs and i'm also not a big fan of ANT.

So if someone wants to migrate the build system to gradle: go ahead :-)

**Comment by AltNico** [comment]
@adrian-bl @aminb
Thank you for your answers but I have one question left before I try to migrate to Gradle: should the project keep support for ANT or use the new build system of Gradle (dependencies, modules, file tree, ...)?

**Comment by adrian-bl** [comment]
It would be nice to keep ANT compatibility if it is trivial to do so - but IMO it is not a requirement.

**Comment by aminb** [comment]
I'm using emacs with some ant integration; so keeping ant would be nice.

But, as long as `./gradlew` commands (clean, assembleDebug, etc) work and I don't have to open up Android Studio for building, removing ant shouldn't be a problem.

**Comment by adrian-bl** [comment]
@AltNico I merged your PR but re-added ants build.xml to keep compatibility with ant (at least for now).
I assume that this shouldn't cause any trouble with gradle / android studio?

**Comment by AltNico** [comment]
@adrian-bl Thank you for merging.

At the top of build.xml it says:
`The local.properties file is created and updated by the 'android' tool. It contains the path to the SDK. It should *NOT* be checked into Version Control Systems.`
Because of this I deleted this file but you can keep it, there is no problem with Gradle / Android Studio.

**Comment by artiescie** [comment]
in case it helps someone... using gradle wrapper from the command line, I get some errors.  

fixed by these diffs:

 // Top-level build file where you can add configuration options common to all sub-projects/modules.
 buildscript {
**+    System.properties['com.android.build.gradle.overrideVersionCheck'] = 'true'**
     repositories {
         jcenter()
     }
@@ -44,4 +45,7 @@ android {
             proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.txt'
         }
     }
**+    lintOptions {
+          abortOnError false
+      }
** }

I am pretty sure this isn't the optimal fix so won't try pull request.  I speak for the silent majority perhaps when i say, my current goal is to survive gradle not to master it ;-) so ... "this works for me..."
