### ISSUE TITLE
Increase font size option?

### ISSUE THREAD

**Issue by anaggh** [vanilla-music/vanilla#170]
Sometimes, I feel the font size used to display the library is a bit less. It is possible to override it with Android: Settings -> Display -> Font size but that makes the other apps installed ugly. Maybe you could include a accessibility feature to increase font size for vanilla music.

Edit: maybe its the padding between the list item and the border or its just my eyes which are spoilt.

**Comment by belanger** [comment]
I second this request.  For now, I used anaggh's suggestion of increasing the size of the system font, but it would be nice if the change could be vanilla-specific.

**Comment by xbao** [comment]
That would be handy. I'm astigmatic(mixed), and I'm always cranking up the size on e-book/apps. I also avoid pushing up the system text size because, as you say, some (most?) apps just don't handle it well. 

Programmatically speaking, I haven't found a clean solution, particularly if it still needs to play nicely with the system font size.

A good first step might be to make Vanilla look good when the system font size is increased to large. I just tried it out, it seems mostly okay with some significant exceptions, such as the song album being cut horizontally: 
![vanilla_large_font_songs_motog2](https://cloud.githubusercontent.com/assets/8990412/9559716/5d255256-4e3b-11e5-91ea-de61228905df.png)
and double lined artists/albums also being cut horizontally:
![vanilla_large_font_artists_motog2](https://cloud.githubusercontent.com/assets/8990412/9559739/05d5b396-4e3c-11e5-9ef4-452bb6856b3b.png)

**Comment by adrian-bl** [comment]
Yeah, the library rows are hardcoded to 44dip.

Hmm.... is there a way to tie a layout to a (maximal) font size in XML?

**Comment by xbao** [comment]
> I changed the 'dip' definition to 'sp' for the library rows (776385e)

Nice! Sounds weird, but makes sense.

**Comment by adrian-bl** [comment]
Closing this as Vanilla now plays well with the systems big font size.

Changing the font size during runtime on our own seems to be rather messy: The only solution i found would be to specify this in the theme - and we already have to maintain 3 themes (holo, material light and material dark) - Adding the font size would require us to maintain and test 6 themes.

But if someone finds a better way to do this: feel free to re-open the bug.
