### ISSUE TITLE
Id3 data via A2DP not correct

### ISSUE THREAD

**Issue by mase76** [vanilla-music/vanilla#177]
Hi!
I use my Android device with Vanilla Music in my car via bluetooth.
The title data displayed in the car is not as it should be.
The id3 categories are not displayed correctly.
The title field is ok. The artist field is empty. The album field shows the artist.
The timestamp does not work at all.

**Comment by un-logic** [comment]
I'm currently running 1.0.30 and experiencing same issue. 'Title' is okay, but 'Artist' is empty although other apps e.g. VLC or Samsung Music behave correctly. Tested with SBH50 stereo Bluetooth headset.
But there is one thing that points out that problem may lie deeper. Using S-view cover with SGNote 3 I've noticed same behaviour on S-view lockscreen controls (any tags other than 'Artist' aren't broadcasted) although standard system notification of Vanilla behaves correctly.
Hope this bug will be pinned and fixed soon. TIA.

**Comment by adrian-bl** [comment]
This is probably caused by commit c28564ae8d0c8024bdead40e96947ef829dda463 
We changed Vanilla Music to never set the artist field & include this information in the album information.

This was done as most ICS devices never displayed the artist field anyway.. but given the fact that ICS is dying, we should probably revert this commit

**Comment by adrian-bl** [comment]
Changed, fixed and pseudo-reverted in https://github.com/vanilla-music/vanilla/commit/e4855e51ebd146e5b77550175f33064ee1e32d43
