### ISSUE TITLE
Improve OPUS header support

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#194]
Vanilla Music & BASTP should support the R128_TRACK_GAIN (https://wiki.xiph.org/OggOpus#Comment_Header) header - assuming that the builtin decoder doesn't take care (the CM version doesn't and the AOSP one is broken)

**Comment by adrian-bl** [comment]
I added opus container support to bastp: https://github.com/adrian-bl/bastp/commit/cfb26e728b85d5eb0752ed68c629fe984a6c641a

So we should replace our in-tree copy. However: I'm still not so sure on how the replay gain stuff should be handled in opus files. (the CM decoder does - currently, not normalize anything)

**Comment by kepstin** [comment]
Hi,

I was involved (at a very minor level) in the ogg opus spec, and I make heavy use of ogg opus files with replaygain in a variety of music players.
My recommendation for tag parsing for maximal compatibility is as follows:

1. The header output gain field must always be applied, in addition to and before any replaygain/r128gain tags present.
2. If the `R128_TRACK_GAIN` or `R128_ALBUM_GAIN` tags are present, use them - ignoring any `REPLAYGAIN_*` tags that may be in the file.
3. If the file does not contain `R128_*_GAIN` tags, but does contain `REPLAYGAIN_*` tags, use the `REPLAYGAIN_*` tags (treat them in the same way as vorbis).

I know the Ogg Opus spec says not to use the REPLAYGAIN tags, but I'm being pragmatic here. Several existing players already read them, because they share tag parsing code between ogg vorbis, ogg opus, and flac. A few players - including rockbox and rhythmbox - don't yet read the R128 tags at all, but only read REPLAYGAIN tags from opus! I've gotten into the habit of writing both tag formats to my ogg opus files.

**Comment by adrian-bl** [comment]
Ok, thanks for clearing this up.

I will change BASTP (our tag reading library: https://github.com/adrian-bl/bastp) to do this.

But i really do not get why Opus supports both the header output gain + the R128GAIN field: What's the point in having to seperate replay gain values?

**Comment by kepstin** [comment]
The thing to remember is that the header output gain field is not a replaygain or normalized volume field. It is simply an arbitrary gain to be applied during audio decoding. It is unspecified whether or not applying this gain will cause the audio to be at any specific reference level.

Only the R128_TRACK_GAIN and R128_ALBUM_GAIN fields are specified to adjust the volume to a specific reference level (when applied in addition to the header output gain field).

Some example situations:

- If the audio file was mastered at R128 levels, the encoder might set the header output gain field to +10dB so it sounds as loud as pop mp3 files when played back in a non-replaygain-aware player, then use the R128 gain tags so a volume-normalizing player can reverse that change.
- In many cases, the header output gain field will be simply set to 0, and only the R128 gain tags will be used.
- If someone uses ReplayGain regularly, but their player doesn't support ReplayGain in opus files, they might store an adjustment to replaygain reference level in the header output gain field, then also include R128 gain tags that adjust to the R128 reference level (approximately 6dB difference)

**Comment by adrian-bl** [comment]
Closing this as the needed code is now included in BASTP
