### ISSUE TITLE
Load Embedded Album Art

### ISSUE THREAD

**Issue by KonomiKitten** [vanilla-music/vanilla#208]
Please add a feature to load Embedded Art from the audio files directly. I've found Android's Internal Media Database to be beyond awful and I don't want to use a folder or image file for every individual song. Embedded Album Art is by the far the best solution. Please add it, thanks.

**Comment by adrian-bl** [comment]
Vanilla Music should actually be able to get embedded media files using Androids content provider.

Does it fail for you on some files or is the quality just awfull?

**Comment by KonomiKitten** [comment]
@adrian-bl I found a work around which invalidates this report somewhat, Vanilla Music is loading the Embedded album art. But for example say if I have a bunch of singles, all with embedded album art but they have no album value in the tags, then Vanilla Music will assign them covert art of the first album in the same directory. I worked around this by setting the album tag on each song to the title enclosed in square brackets. This made Vanilla Music show the correct cover art for each song.

What seems to be happening from my limited view point, is Vanilla Music looks for embedded art but associates it with the album tag rather than the song itself.

**Comment by adrian-bl** [comment]
That happens because we use the album id as the cache key.

I'm not sure if there is an easy way to detect + avoid this behaviour (and i consider it to be somewhat unlikely to have a song with no album information)

**Comment by KonomiKitten** [comment]
@adrian-bl I listen to a lot of Vocaloid songs, and they're commonly released with no album information because most artists making them just don't make albums. There's also a few artists on SoundCloud I know of that releases songs without releasing them in albums either.

**Comment by berrythesoftwarecodeprogrammar** [comment]
this has bugged me for SO long. took me a while to figure out that androids media database just sucked. a lot, if not most, of my music, has no album tag, but a lot of those, still have art. even when they do have album information, android still shows art for other albums by the same artist instead of the correct one. its absolutely terrible and everytime i try turning album art back on i end up turning it off quickly because its never accurate. there should definitely be an option to read the album art for EVERY song when playing that song. they shouldnt be mapped to certain tags and cached so badly. every mp3 has the possibility of having different art. every music player on desktops understand this. i think its odd this isnt the default behaviour for any android music app

**Comment by KonomiKitten** [comment]
@berrythesoftwarecodeprogrammar I've found the best work around is to do the following:

For actual singles set the single name to: Single Name

For single songs that have no album name put in the album field the song title in [ ] this lets you know it's not a true single and lets album art work right: [Track Title]

This is my current work around and it works well and lets you know that the track is not a true title.

**Comment by berrythesoftwarecodeprogrammar** [comment]
ah i might try that. i'd rather not have to modify all of my mp3s tho

**Comment by Piscium** [comment]
I discovered this player today at F-Droid. Thanks for sharing it!

About half of my songs has tags and embedded pictures, and the other half has neither. So if I have a song with tag and picture followed by 3 songs without, the picture of the song that has it is displayed for the next three songs. That is confusing. The fix should be in my opinion that if the song being played has no picture than no picture should be shown.

**Comment by berrythesoftwarecodeprogrammar** [comment]
the problem is more than that though. if a bunch of songs by an artist have no album listed but have different artwork, it will continue showing the same one. it should just behave like a normal mp3 player and load artwork from the file when playing it. and if theres no artwork, show no artwork

**Comment by Piscium** [comment]
I agree with what you said: "it should just behave like a normal mp3 player and load artwork from every file when playing them. and if theres no artwork, show no artwork".

"No artwork" in the context of the Vanilla player is a blank background with what looks like a light gray CD superimposed on it.

**Comment by adrian-bl** [comment]
I hacked up some way to make the cache key configureable: https://gist.github.com/adrian-bl/fe851d510b4f1e61bca9 .. and then realized that android does exactly the same as we used to do:

Android (at least 5.x) will only store ONE cover per album, even if each song has a different (embedded) cover.

I'm sorry, but there is nothing we can do as we use androids media framework to extract embedded artwork.

**Comment by Piscium** [comment]
What about this: you check if the song has an ID3 album tag, and if it does not you remove the artwork from the display. Is that possible? That would solve the problem for me.

**Comment by Piscium** [comment]
Hi Adrian,

You said "Android (at least 5.x) will only store ONE cover per album,". I don't quite understand that, at least in the general case.

I will tell you about my own case. On my PC I have songs in many folders, some songs have tags others don't. I create a playlist on the PC and then I use a simple Python script that copies all songs to one folder in the PC (just songs, no album art) and then the script creates a simple m3u playlist that has the names of the songs. I then copy this folder to my Android tablet. When it arrives at the tablet there is no album art as such, there are songs with tags and embedded artwork, and songs without.

**Comment by adrian-bl** [comment]
> What about this: you check if the song has an ID3 album tag,
> and if it does not you remove the artwork from the display. Is that possible?

No, because (as mentioned in my previous comment), Android itself will claim that the song has an album artwork.

> You said "Android (at least 5.x) will only store ONE cover per album,".
> I don't quite understand that, at least in the general case.

Android provides a 'builtin' media database: Every media on your device (mostly songs and videos) are indexed and assigned a unique id.

For songs, the database will look something like this:

```
+------+--------+-------+----------+------+
|  ID  | ARTIST | ALBUM |   TITLE  | PATH |
+------+--------+-------+----------+------+
|   3  |   10   |  12   | Foo Bar  | /foo |
|   4  |   10   |  12   | Blabla   | /bar |
|   5  |   10   |  13   | Blurgs   | /xyz |
+------+--------+-------+----------+------+
```

So lets say: you are playing /foo: Vanilla Music will look up the media database and query the album artwork of song 3, see: https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/CoverCache.java#L412 - Androids bultin media framework will then return the Album Cover (as a bitmap) back to vanilla music.

The same happens if you start playing '/bar': Vanilla Music will query the album artwork of id 4.
However: In this case, Android will notice that both songs share the same album id and will return the same artwork as it did for song 3, or any other song sharing album id 10.
