### ISSUE TITLE
Previous track button problems

### ISSUE THREAD

**Issue by snelltheta** [vanilla-music/vanilla#232]
In shuffle mode, it will go to a random track, not different from forward. Suggestion: make it so it will remember the last tracks.

When pressing previous track button, expected behavior is to start at beginning of current track after a reasonable amount of time has passed. It currently doesn't.

**Comment by adrian-bl** [comment]
> In shuffle mode, it will go to a random track, not different from forward.

No - it doesn't by default. It only does this when you enabled the 'continuous shuffle' option or if you hit the end/beginning of the queue (eg: hitting back on track 1)

> When pressing previous track button, expected behavior is to start at beginning of current track
> after a reasonable amount of time has passed. It currently doesn't.

You mean the on-screen '|<<' button?
This would IMO be a very surprising behaviour: i do not know any software which does this (VLC, Gmusicbrowser and co don't) for on screen buttons. But note that we *do* skip to the beginning if the user pressed a hardware-back button and played more than 2.5 seconds of the song have been played.

**Comment by snelltheta** [comment]
"You mean the on-screen '|<<' button?"

Yes, I do. This behavior exists on the HTC default player, LG default player, Motorola player, iOS Music app, Apollo, Pretty Good Music Player, Timber, and I seem to recall MXPlayer did the same.
Due to the popularity of the behavior in other players, this is where I gather the usability of the skip track back button.
Trained, really.

Besides that, it's very useful in a shuffled mode in order to listen to the same song twice with minimal effort. 

Without continuous shuffle, this can be a disastrous effect for a phone without available hardware buttons, due to the inability to get back. This is why the other issue was opened about the shuffle, as well.

Also, thanks for the input on the PGMP issue.

**Comment by adrian-bl** [comment]
Apollo is a fork of com.android.music (the AOSP music app) and all other vendor-players are probably also forks, so they inherit this from a single code base (..and Timbre is an Apollo fork).

But i agree that it seems to be a common behaviour (play music also does this, including some weird auto-play logic when hitting the widget).

@aminb What is your opinion on this? I do like the current behaviour and do not see a big issue with it as the continious-shuffle option is disabled by default anyway.

**Comment by aminb** [comment]
IMHO I think having an option to make `|<<` behave the same as the hardware back button would be nice (especially if in random mode) and there's been times I wished it was like that. However I don't think it should be the default behaviour, or if it is, there should be an option to toggle it because I don't feel like always having to press the back button twice to go back a song.

**Comment by adrian-bl** [comment]
> However I don't think it should be the default behaviour, or if it is, there should be an option to toggle 
> it because I don't feel like always having to press the back button twice to go back a song.

Hmm.. we already have (imo) way too many config options.
But how about this: We keep the in-app controlls as they are ( = the buttons in the FullPlaybackActivity) and only change the behavior of external buttions ( = the notification and widgets) to match the hardware-button behavior?

**Comment by aminb** [comment]
Yeah that could also work!

**Comment by xbao** [comment]
My 2c is that it would be confusing to have the same icon behave differently in different places. Maybe we could use a double arrow left for moving back a song and a single arrow left for going back to the beginning? 

> Hmm.. we already have (imo) way too many config options.

I like all the options! As long as it does something sensible by default, I see all the options as one of the strengths of vanilla.

**Comment by adrian-bl** [comment]
> My 2c is that it would be confusing to have the same icon behave differently in different places.

I agree but OTOH it is also confusing that swiping back wouldn't do the same thing as hitting the back button in the FullPlayback activity.

(Also: Just changing the behavior of 'external' buttons would be simpler code-wise ;-) -> https://gist.github.com/adrian-bl/134768949d24040523f6)

That said i'm still not really sold on implementing this feature as the current behavior only turns out to be a problem in the (non standard) continuous shuffle mode.

**Comment by snelltheta** [comment]
Continuous shuffle mode was only an example, and perhaps I shouldn't have brought it up, as it should be a separate issue. The problem, as a user, is that every mp3 player, iPod, CD player (portable or otherwise), iPhone, and most Android applications, that I have used have exactly the same behavior for the back button (software and hardware interface alike): one press after a reasonable amount of time will send you to the beginning; a second press to skip to previous track.

**Comment by adrian-bl** [comment]
This diff should do it for all user interactions:
https://gist.github.com/adrian-bl/33841b8d087cb04426d6

Turned out to be less ugly than expected (i had the impression that more code calls into PlaybackService.shiftCurrentSong() which was renamed into the (ugly) shiftOrRewindCurrentSong() )

I'll target this (+ a config option to turn it on/off) for the 1.0.34 release.
Hmm.. thinking about it: we probably should count 'rewinded' songs as played (after reaching ~75% or so?)

**Comment by adrian-bl** [comment]
implemented via: https://github.com/vanilla-music/vanilla/commit/655d0719018d633dbe662bce9f536ccf146d82bd

**Comment by xbao** [comment]
>  The problem, as a user, is that every mp3 player...

Yeah, now that I think about it Vanilla was the first media interface I had used where pressing the previous button goes back to the last song unconditionally.

> Hmm.. thinking about it: we probably should count 'rewinded' songs as played (after reaching ~75% or so?)

Sounds reasonable to me :)
