### ISSUE TITLE
Library Screen refuses to automatically open Files-tab if other tabs are visible

### ISSUE THREAD

**Issue by R0M4N0F5K7** [vanilla-music/vanilla#241]
Is it maybe only my phone - because I know that many people use this player because of the nice file browsing abilities...
It's not a big issue but actually really annoying in every day use:

When the library screen tabs are re-ordered in the settings, the app should/does always open the tab on first place automatically. Only if the first tab is the 'Files'-tab the app automatically opens the second tab when accessing the library screen which is quite impractical and illogical.

**Comment by adrian-bl** [comment]
Oh, that was a stupid bug:

We didn't save the position of open tabs with an active limiter (eg: displaying songs of an album), but the filesystem adapter would almost always have a limiter, so it never got saved.

This should be fixed in: https://github.com/vanilla-music/vanilla/commit/36c63ff57ae2061a9fdccadfe607aede2b734466
