### ISSUE TITLE
Playlist managment

### ISSUE THREAD

**Issue by mase76** [vanilla-music/vanilla#242]
Hi!
I think, vanilla should implement its own playlist managment, as the one from android has some issues. For example, whe the music is stored on the external sdcard, unmounting removes all the titles from the playlists.
Also some basic sorting operations should be added, also exporting.
There is no (free) 3rd party app, which does this.
For saving the playlists you have to copy the database files by hand on a rooted device.

**Comment by mathstuf** [comment]
See #3.

**Comment by Piscium** [comment]
Sorry for hijacking this issue! I am looking for something like a Google Groups forum where people can ask support questions about the Vanilla player. Is there such a thing?

The question I have is is: Is there a way to show in the Queue display or Playlist X display the buttons to stop/pause a song?

**Comment by aminb** [comment]
@Piscium We don't have a Google Groups or mailing list (not at the moment, at least), so feel free to open up issues here on Github and we'll try to address them.

About your question, right now there's no way to do what you asked. But I've been thinking about improving the whole workflow and I'll open another issue with @adrian-bl, and we can discuss what things we can do to make playing/pausing and the whole thing a bit easier and more accesible.

**Comment by Piscium** [comment]
Thanks. The only way to "sort of" doing what I asked for is if I am in the Queue display and pull the Notifications mini-screen down, then I get the Pause button there, but this is not ideal.

**Comment by aminb** [comment]
You're welcome. Yeah the notificaion is always accesible but I agree it's not the best way to interact with the app when you're inside the app. Hopefully we can come up with something to make this easier.

**Comment by Piscium** [comment]
Last support question for today: There is a series of symbols that indicate if the song should be played once, or 1 song repeated, or the whole playlist repeated or not. Then there is one icon that has two squares, one with one dot, the other with two, at an angle with each other. What does this icon mean?

**Comment by aminb** [comment]
That's the 'Random' mode, and the two 'squares' you mentioned are a pair of dice. This means that vanilla will choose the next song at random (and append it to queue) if I recall correctly.

Note that this is different from the Shuffle button on the bottom left corner, in that the shuffle button will shuffle the items already in the queue.

You can long-tap both those button to see the options textually.

**Comment by Piscium** [comment]
Thanks a lot. I did not know about the long tap. 
Good night.

**Comment by adrian-bl** [comment]
This question came up already a couple of times and i think it would make sense to have some basic user documentation.

I opened issue #262 to track this

**Comment by Piscium** [comment]
Another support question in this hijacked issue as there is no Google Groups forum!

If in the Queue screen if I click the three dots then Empty queue, the queue does not get emptied, but instead gets two songs that I did not put in there! If I click in a playlist it gets put in the queue and these two extra songs disappear, but... after the queue is played to the end, new songs keep appearing at the end of the queue. It is like the hand of God does not want the music to stop! 

It is like this: there are two songs at the bottom of the queue, the one being played and another. After one song gets played another appears so there is always in the queue one song after the one being played!

Is this a feature or a bug? I am using the latest Vanilla in F-Droid, with CyanogenMod v. 12.1 (based on Android 5.1). I noticed that there is at least one issue in the Android media framework with playing small silent files, and that is the reason why I installed Vanilla, because the default CyanogenMod player hangs. A similar issue happens with Timber. So if the above is an issue it may not be an issue in Vanilla but in the media framework.

**Comment by adrian-bl** [comment]
> It is like the hand of God does not want the music to stop! 

That's because you activated the endless-random mode (= indicated by the two dices)
In this mode, vanilla music will always auto-append a new song at the end of the queue

**Comment by mathstuf** [comment]
Please open new issues rather than continuing to hijack this one. Some of us care about the issue this is actually related to (though #3 is probably better for that anyways since this is basically a duplicate and there's more information there). Thanks.

**Comment by Piscium** [comment]
@adrian-bl Thanks.

@mathstuf Sorry, but if I had created a new issue it would be immediately closed as it was not a real issue. I think that what I will do that if I have another support question is to create a issue dedicated to random support questions so as not to disturb people and to avoid creating lots of unnecessary issues. There is sometimes a fine line between support question/bug report/feature request.

**Comment by adrian-bl** [comment]
@Piscium 

> Sorry, but if I had created a new issue it would be immediately closed as it was not a real issue. 

Uhm.. no: But hijacking old bugs is out of question. Stop doing this. Now.

Also please note that this is an open source project and we do not have the resources to answer support questions on a regular basis.

**Comment by adrian-bl** [comment]
closing this as a dup of #3
