### ISSUE TITLE
Failing to start on Android 4.0.3

### ISSUE THREAD

**Issue by trmusson** [vanilla-music/vanilla#252]
Since upgrading from version 1.0.33 to 1.0.34, Vanilla Music fails to open. Selecting its launcher gives the message "Unfortunately, Vanilla Music has stopped", and the app's user interface does not appear at all.

Downgrading to 1.0.33 gets me a working Vanilla Music again.

My phone's a Huawei G600 running Android 4.0.3, and I get the same behaviour from a virtual device running Android 4.0.3 in Android Studio. Please let me know if there are more details I should give you.

I love Vanilla Music, thanks for your work :)

**Comment by adrian-bl** [comment]
Oops: I never tested 1.0.34 on API-Level 15 (= pre jellybean).

The crash is the result of the ViewPager update in 1.0.34.
Commit https://github.com/vanilla-music/vanilla/commit/5589f9eebc0be31a6c45f235cf08b8e6f528b4b1 should fix the issue (it does for me in the Emulator running the 4.0.3 image)

If you have the SDK installed: feel free to compile + install the current HEAD (should be stable)
Otherwise, wait for 1.0.35 (1.0.34 includes mostly fixes for Android 6)

**Comment by trmusson** [comment]
I can confirm that the current HEAD works nicely on my G600 - the problem is fixed.

Thanks, I appreciate it very much :^)

**Comment by adrian-bl** [comment]
Thanks for the feedback.

I already tagged the head as 1.0.35, so the fixed version should show up soon on f-droid
