### ISSUE TITLE
Show Album instead of Artist in Library

### ISSUE THREAD

**Issue by dakesew** [vanilla-music/vanilla#261]
As I listen to a lot of soundtracks, when looking at the individual songs, could there maybe be an option to show the albumname or use the same style as the queue view (album, artist) in the grey text under the Titlename?

**Comment by aminb** [comment]
So, if I understand correctly, you're suggesting we add an option to display the Album instead of Artist for the list items in the "Songs" tab?

It shouldn't be too hard to do this if you've done Java programming ? What I'm trying to say is that in case this doesn't get implemented, you could clone the repo and make the change and build a custom version for yourself.

@adrian-bl What are your thoughts on this?

**Comment by adrian-bl** [comment]
I wouldn't make this an option: Displaying songs in the library in the same format as in the queue (title\nalbum,artist) makes sense.

@dakesew if you would like to give it a try yourself: feel free to send me a PR or a patch - if not: just wait and i'll implement it myself when i have time.

As @aminb said: The code to change is at https://github.com/vanilla-music/vanilla/blob/e7a9bb74c047725219a34c9624405df70c9ee69e/src/ch/blinkenlights/android/vanilla/MediaAdapter.java#L499 and should behave like https://github.com/vanilla-music/vanilla/blob/master/src/ch/blinkenlights/android/vanilla/ShowQueueAdapter.java#L72

**Comment by adrian-bl** [comment]
implemented via: 0e9f5b590aecd3a811886b242a9a0fc006e4ada0

**Comment by xbao** [comment]
Excellent, +1. Didn't realise so many of my songs have no artist.
