### ISSUE TITLE
Adding a folder to the queue - selecting "Play" adds nothing

### ISSUE THREAD

**Issue by sellsky** [vanilla-music/vanilla#270]
I'm not sure, how would I add a folder (tree) to the queue?

I suppose selecting "Play" on a folder in Folder Browser should add songs from this folder to the queue.

So, I browse my music tree, choose a folder, long press on it, select "Play", and then I see a message "0 songs playing", and that's it. However, should I enter this folder and select "Play" on an arbitrary music file there, Vanilla plays this file just fine.

"Enqueue", "Add to Playlist..." etc acts the same way.

I tried it on my phone (Android 5.1) with music tree mounted from my home server via EasySSHFS, and on my Android Car Audio (Android 4.2; that's where I wish to use Vanilla) with music tree mounted from an external USB SSD.

Is there anything wrong with my devices, or something? What diagnotics can I provide?

**Comment by adrian-bl** [comment]
That's because the files in your SSHFS mounted filesystem are probably not indexed in the media database:

Vanilla Music uses Androids Media Database to recursively discover files in subfolders.
So if the folder is not present in the media database, it will be unable to find any files to play (single files work as it will then use some special code to handle a single non indexed file)

The only solution to play your files from sshfs is therefore to index them using something like 'SD Scanner':
https://f-droid.org/repository/browse/?fdid=com.gmail.jerickson314.sdscanner

**Comment by sellsky** [comment]
Thank you Adrian!

**Comment by Dreadeath** [comment]
When I copy music files by sshfs to external SD card inside my phone, I get the same behavior. I think it's a bug, because, well, it is not what I expect as a user, I should not go to github issues and find a solution to use 3rd party app, this is strange. At least it should be mentioned somewhere that folders aren't really folders, but Android Media Database.

**Comment by xbao** [comment]
I think that's a good point, seeing "0 songs added" isn't particularly helpful. Perhaps we could make a check in that case to see if the MediaStore is out-dated and let the user know somehow?
