### ISSUE TITLE
An empty genre cannot be deleted

### ISSUE THREAD

**Issue by santiagoll** [vanilla-music/vanilla#286]
I am a new vanilla user and very interested in using the genres to organize my music collection.

Unfortunately I have found that when I long-press on a music genre and then select "delete", the genre is not deleted (even though if the genre has zero associated songs)

Thank your help and for this great program!

**Comment by adrian-bl** [comment]
This is actually an annoying Android Bug: Android will *never* forget a Genre it has seen - even if the Genre does not include any songs on the device.

But given the fact that google doesn't seem to fix this bug (is has been there since forever), we should probably find a workaround for this solution (we already do hacky things to filter the genres anyway)

**Comment by Almtesh** [comment]
You could display only genre which are not empty. I don't know if it could be a heavy computing, but that could be a good start.

**Comment by adrian-bl** [comment]
Fixed via https://github.com/vanilla-music/vanilla/commit/563b01ee6c71779a1fb16c8ec45ae58f542e74d9 : Vanilla Music will now hide empty genres.

**Comment by santiagoll** [comment]
I have tested it today after upgrading to Vanilla 1.0.38 and it is working fine!! Great job. Thank you very much
