### ISSUE TITLE
Redesign library slide controls

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#319]
The bottom bar controls in the library view need a redesign:

We could make them bigger (?) and (at least) include the progress bar.

Example:
![Mockup](http://i.imgur.com/PmyWfQR.png "Mockup")

**Comment by xbao** [comment]
Size-wise they're good for me. Progress bar would be excellent. 

Maybe a dropshadow between the controls and the queue?

![vanilla_draw_320_cropped](https://cloud.githubusercontent.com/assets/8990412/14402621/a03ff50c-fe7e-11e5-89d2-4966458e245f.png)

**Comment by adrian-bl** [comment]
The shadow looks fine to me, but wouldn't it be simpler to just use android:elevation for this?
See https://github.com/vanilla-music/vanilla/commits/elevation

This would have the advantage to do nothing on ICS out-of-the-box (drop-shadows are unusual on Android 4.x)

**Comment by TheLastProject** [comment]
Instead of hacking in the progress bar, which basically makes the now playing screen useless and adds to the already duplicate functionality that was introduced with the slide controls, what about following the CyanogenMod example and modelling it as follows (-> means drag up):
Library screen -> Now playing screen -> Queue

This allows the user easy, quick access to any screen they'd like, at most 2 drags away, instead of the library and the queue being easy to switch between, yet the now playing screen being "disconnected".

To further explain my point, here are some screenshots:

You start off at the library screen:
![Library screen](https://lut.im/99MQCW6T9r/SqWfWfyVCB3PrmMn.png)

Then, you drag up, showing the now playing screen:
![Now playing screen](https://lut.im/sWAqIek1iD/YBCezSTjdm9sJKjZ.png)

Then, dragging up, you see the queue:
![Queue screen](https://lut.im/T5ZeRQKR6x/1RufnfsTq2FP7Z8y.png)

**Comment by xbao** [comment]
> The shadow looks fine to me, but wouldn't it be simpler to just use android:elevation for this?
> See https://github.com/vanilla-music/vanilla/commits/elevation
>
> This would have the advantage to do nothing on ICS out-of-the-box (drop-shadows are unusual on Android 4.x)

Sure, though it also means that the usability problem that the shadow is solving is still present on ICS. I'm happy with either approach, it's a small issue in the scheme of things.

**Comment by adrian-bl** [comment]
> Sure, though it also means that the usability problem that the shadow is solving is still present on ICS. 

The shadow wouldn't be visible on ICS anyway due to the black background:
![](http://i.imgur.com/WNPTzzK.png)

We could add a holo-colored bar on ICS, but sharp edges are not that uncommon on 4.x and its user base is (slowly but surely) shrinking.
I merged the elevation branch into the master for now as it reduces the amount of code + views (and makes me happier ;-) )


@TheLastProject The main point of the slide-up-queue was to make the view accessible from the Library and the full playback view with a quick gesture. Adopting Elevens workflow would take us back to the start.

**Comment by adrian-bl** [comment]
I created an 'action-breakup' branch, see: https://github.com/vanilla-music/vanilla/tree/action-breakup

The branch moves some stuff from FullPlaybackActivity to a new class and also adds the seek-bar to the library view.

The design is not meant to be finished, i just wanted to get the core-function up & running.

**Comment by aminb** [comment]
/u/smitt75 on reddit [suggests](https://www.reddit.com/r/vanillamusic/comments/4hv7kc/love_vanilla_music_but/) that we make the bottom bar persistent throughout the app. For example, right now the bottom bar is missing in the playlist view.

**Comment by adrian-bl** [comment]
I agree, but this will require quite some work, as the playlist editor is a different activity.

We therefore either need to rewrite the playlist editor (to be part of the LibraryActivity) or to put the bottom bar into the playlist editor
