### ISSUE TITLE
Swipe down doesn't allow "Show queue" action

### ISSUE THREAD

**Issue by ToNIX-** [vanilla-music/vanilla#328]
Has this recently changed? I was able to swipe down to show the queue in previous versions.

The action it not in the list anymore, I have to press the 3 dots menu and press "Show queue".

**Comment by adrian-bl** [comment]
Yes, this was removed because you can now drag the controls upwards

**Comment by richq** [comment]
Just for the record, I miss this option too. Swipe up can still be bound to show other screens, and there's a menu option to show the queue. It's not like swiping up is no longer bindable, nor was the queue screen removed. Sad that it had to go.

Moving the controls up like that looks cool and must have been a lot of trouble to implement, but I find it more fiddly to use than the old bound option. Now I need to start the swipe exactly on top of the controls. Not too low or Google Now tries to open, not too high or it will trigger any bound swipe-up gesture. I have to start right on top of that 1cm control strip, and swipe for quite a long way or it falls back down. Before I could swipe pretty much anywhere on screen, and not have to swipe for such a long way. It was *perfect*.

So, er, yeah. It ain't coming back, but at least I've ranted on the internet now so that's made it better ;-) Time to get used to the new way of doing things...

**Comment by adrian-bl** [comment]
@richq the feature will get re-added due to popular demand ;-)

See: https://github.com/vanilla-music/vanilla/issues/341

**Comment by ToNIX-** [comment]
Yay, swip down makes to show queue makes sense, thanks @adrian-bl !
