### ISSUE TITLE
Tapping artist once queues every single track

### ISSUE THREAD

**Issue by inspector71** [vanilla-music/vanilla#370]
Hi

Weird bug maybe.

I tap an artist with one short tab. That artist might have a couple of albums in my library.

Next thing I know I see a message telling me over 3000 songs queued 😀

Whoops?

Android 5.0.2

Vanilla 1.0.40

**Comment by adrian-bl** [comment]
Does this happen for all artists?

**Comment by inspector71** [comment]
I haven't tested every artist however I just chose a few at random and yes
it happened for each one I picked.

I don't want to confuse or misdirected your debugging however I recently
tweaked a setting that seems related, for the first time since I started
using the app. It may be coincidence but the problem seems to have started
since then.

I think the settings were library screen, default action and default
playlist action. I set them both to play all. I thought this setting would
queue all songs from the artist I tapped on rather than all songs from all
artists.

Thanks for your hard work on this app.

**Comment by adrian-bl** [comment]
>  I think the settings were library screen, default action and default playlist action. I set them both to play all. 
> I thought this setting would queue all songs from the artist I tapped on rather than all songs from all artists.

Ah, ok: Yes: This is the expected behaviour with this configuration:

The default-action-play-all causes Vanilla Music to (recursively) play all visible items on the screen:

Eg: If you see 3 albums and touch one of them, all 3 albums will get enqueued (just like hitting the 'play all' item at the top of the screen).

What you probably want is to configure this to 'Play': This causes Vanilla Music to (recursively) play the *tapped* item.
