### ISSUE TITLE
Play next song after directly selecting one song

### ISSUE THREAD

**Issue by madduck** [vanilla-music/vanilla#418]
If I opt to play song 2 in album "foo", playback pauses after the song. I'd prefer to be able to configure it to just start playing song 3.

Maybe this is related to the behaviour that I can swipe left/right to switch songs, but pressing on the Next/Prev buttons on the playback screen actually doesn't advance or go back, it just plays the same song again.

I can try to submit a screencast if it helps…

**Comment by adrian-bl** [comment]
yes: please submit a screencast. Also make sure you are not in the 'repeat single song'-mode

**Comment by madduck** [comment]
Curiously, even swiping left/right doesn't seem to work anymore. Please see the screencast.¹ Towards the end, note carefully how I am pressing the `>|` and `|<` buttons, yet the song just starts from the beginning in both cases.

¹) http://scratch.madduck.net/vanilla_music_screencast_next_does_not_advance.mp4 (Github does not allow video uploads.

I was unable to reproduce this, but there have been times when a completely random song would be played "next", and then the same song again after I hit "next" again.

**Comment by adrian-bl** [comment]
Thanks for the screencast.

But that is the expected behaviour:

* The queue has only one item and the player is in non-repeat mode.
* So hitting 'next' or 'previous' wont do anything because we are at the end + the beginning of the queue
* Slide still works because of - reasons: sliding always works and simply skips from end->start of the queue :-)

**Comment by madduck** [comment]
Okay, I understand this, but couldn't it be (trivially) made configurable to advance to the next item in the context of the file I started to play once the queue empties out?

If I wanted to play an album from track 3 onwards, I'd have no other way than to queue the entire album and skip two, or queue each track individually from 3 on. Neither of those are optimal, and it's not what the others players are doing either.

I briefly considered the thought ot just queuing all remaining tracks in a directory, but I don't think one would want to actually mess with the playlist. I think that once the queue ran dry, then some sort of default behaviour can kick in. And this behaviour right now is to stop playback, but it could be to resume at the next track in the same album of the last song.

**Comment by adrian-bl** [comment]
> Okay, I understand this, but couldn't it be (trivially) made configurable to advance to the next
> item in the context of the file I started to play once the queue empties out?

I think the best solution would be to simply long-press at the song and then hit 'Play All' which will start playing the song and enqueues all visible songs which come after the selected item.

Isn't that the behavior you expect to see?

**Comment by madduck** [comment]
That's exactly what I was looking for! Maybe that can/should be renamed to "Play From Here" or so? What do you think?

**Comment by adrian-bl** [comment]
Maybe, but the translation for it might take too much space in some languages, eg. in German: 'Von hier an abspielen' is way too long ;-)

Maybe we just need a nice user manual / faq on http://vanillamusic.io

**Comment by madduck** [comment]
"ab hier spielen" ;)

**Comment by pascallaprade** [comment]
Starting an album not with the first track is something I do quite often.

Since what we want in this case is already implemented via the context menu, maybe you could allow users to change it in the preferences?

I see it is already possible with playlists to change their default behavior, having the exact same options as the context menu.

**Comment by adrian-bl** [comment]
Setting play all as the default action in the library is already possible

**Comment by madduck** [comment]
I just had a chance to play with this again and have to say: there is no option to "play all" in the context menu of an individual track, when I am in the "Files" browser. It seems to exist only in the library view.

**Comment by pascallaprade** [comment]
You mean changing the library default from "Explore" to "Play all"? What it does here is queue my entire library if I select an album, where I only want to open an album and then choose the song from which to start. It sure does "play all", but not in the way we mentionned above.

Or maybe is it just that it's another parameter I missed in the options?

**Comment by arromdee** [comment]
Right now, the library default which says "expand all" is really "expand all, or play if on an individual song".  What we need is an additional option "expand all, or play all if on an individual song".

I already suggested this at https://github.com/vanilla-music/vanilla/issues/413 but it was closed.

**Comment by pascallaprade** [comment]
I indeed think it would be a good thing to allow users to set this as a default behavior separate from the "Explore" default as it is now.

I didn't see the closed bug, thank you for sharing!

It eludes me as to why it has been closed since long-pressing is not equivalent to setting a default behavior.

I don't have experience on Android programming yet, but if the maintainers don't have time for this feature, I would gladly see if I can write a patch for this! I think it's always a good thing to allow users to set different for defaults, especially when the can already use the feature on a per-case basis.

**Comment by arromdee** [comment]
You don't need to *write* the patch.  If you want the patch (or an executable) email me at arromdee AT atnex.net.

It also has a patch for https://github.com/vanilla-music/vanilla/issues/421 and saves the location in the track on every pause instead of a minute afterwards.

**Comment by adrian-bl** [comment]
> What it does here is queue my entire library if I select an album

You can always tap the ```>``` icon in the library row to expand it.
