### ISSUE TITLE
Fails to remember progress of played track when closed

### ISSUE THREAD

**Issue by paul70078** [vanilla-music/vanilla#419]
Since one of the last updates of the app, the app forgets the progress of the current track when it is shut (or forced to shut) So it starts playing the track from the beginning

**Comment by adrian-bl** [comment]
The code saving the position was not touched in ages, but i wouldn't be surprised if it was doing odd things sometimes.

What version of Android are you using? Did you recently upgrade?

**Comment by paul70078** [comment]
I'm using Android 6.0.1 on a Sony Xperia Z5 Compact. I haven't upgraded recently. It may sound strange but I think it began after I've installed Pokemon Go.I discovered that when I open Pokemon Go it pauses the music and destroys the Notification and Vanilla Music forgets the progress. The only way around this is to open Vanilla Music before Pokemon and switching back to Vanilla Music after the Music stopped. Then I won't loose the progress. 

I hope I could help :)

Am 4. August 2016 20:22:37 MESZ, schrieb Adrian Ulrich <notifications@github.com>:

**Comment by adrian-bl** [comment]
Just had a look at this and the code seems to work as expected:

If you hit pause (or something else steals the audio focus), we will wait 60 seconds - after this, the equalizer is released and the state is saved.

I suppose , that in your situation, we just get killed earlier than 60 seconds *and* that android does not call onDestroy() (which would also save the state) because it needs to free memory quickly.

So there is not much we can do.
