### ISSUE TITLE
Encoding issue for metadata

### ISSUE THREAD

**Issue by davidschlachter** [vanilla-music/vanilla#461]
I have several tracks that show up in Vanilla Music with the character encoding mixed up, e.g. 

![screenshot_20161103-092656](https://cloud.githubusercontent.com/assets/8271268/19967914/9932148e-a1a8-11e6-95e9-3b9db8cf7555.png)

Here's the output of `mp4info`:

![capture d ecran 2016-11-03 a 09 30 00](https://cloud.githubusercontent.com/assets/8271268/19967783/2619cdf2-a1a8-11e6-8e57-c82ddb3ee80e.png)

And here's the audio file:  

[2-05 When We_re Alone.m4a.zip](https://github.com/vanilla-music/vanilla/files/569069/2-05.When.We_re.Alone.m4a.zip)

Is the default encoding not UTF-8? How is the encoding for metadata determined? Is there a problem with the file?

**Comment by adrian-bl** [comment]
There is nothing wrong with the file: This is (unfortunately) a bug in Android itself where the media scanner tries to be smart and 'guesses' the Encoding of files (even if the format clearly defines a charset)

Unfortunately, there is not much we can do about this right now as this is a bug in Android itself (which might get fixed upstream at som point - or maybe not)

Given the fact that we are already plagued by quite a few shortcomings of Androids media database, we started to (think about) implementing our own media database which should not suffer from such issues (and even if it does: then we can fix it ourselfs) (See #460)

**Comment by adrian-bl** [comment]
The new 'media database' is finally there and we already do have an option to use 'Bastp' (our own tag reader implementation) instead of Androids tag reader for certain file types.

Unfortunately, M4A is not yet supported - So i opened a bug about this on the issue tracker of Bastp (https://github.com/adrian-bl/bastp/issues/5) and will close this issue: Once the issue in 'Bast' has been fixed, it will automatically also be fixed in Vanilla Music.

**Comment by adrian-bl** [comment]
Just fyi: the tag reading library we are using is now able to parse M4A files, so vanilla music 1.0.50 schuld fix this issue (if the internal tag reader is enabled)
