### ISSUE TITLE
Import playlists

### ISSUE THREAD

**Issue by adrian-bl** [vanilla-music/vanilla#474]
Vanilla Music should (at least on its first run) try to import existing playlists.

**Comment by adrian-bl** [comment]
Implemented in head

**Comment by mase76** [comment]
I put m3u playlists to the /storage/emulated/0/Playlists folder. But they are ignored.

**Comment by adrian-bl** [comment]
They are only imported on the first scan (or if you flush the database and do a re-scan).

We currently do not support 'on-demand' import/export of playlists

**Comment by mase76** [comment]
I flushed and did a rescan. No playlists were imported. Where else must I place the m3u files?

**Comment by adrian-bl** [comment]
They need to be indexed by Android itself: We never ever read m3u files directly - we just import what is in androids media library if our database happens to be empty

**Comment by mase76** [comment]
It worked after I re-enabled the stock music app. I disabled it before. Seems that Android does not import playlists without the music app.
Does Vanillas own library include the playlists after they are recognized, or are they still handled by Android?

**Comment by andiandi13** [comment]
@adrian-bl As we can import system library playlists into Vanilla, would be hard to export playlists created by Vanilla _to_ android system library ? 

Because it's quite pointless right know to create playlists with Vanilla since we can't export them and may lose them too. Yet its so convenient to create playlists with Vanilla ! ...

If we could be able to do it, all we have to do is Vanilla>System>m3u (the opposite is possible right now as you know).
