### ISSUE TITLE
Got message "You are using an ILLEGAL.... " after running the code

### ISSUE THREAD

**Issue by ShreyashPromact** [vanilla-music/vanilla#484]
I have to raise this issue again because the original one is closed without its solution or without explaination. You can refer that at this link: [#483](https://github.com/vanilla-music/vanilla/issues/483)

Hi, I have just used this repository code and check it. But I got below toast message in initial landing screen and also in the screen after that.
"You are using an ILLEGAL clone of Vanilla Music :(
You can get original at http://vanillamusic.io/
The original version is completely ad-free and open source (unlike the version you are using)"

So, what's wrong happening here?

Please guide me to resolved this issue.

Thanks.
Sincerely,
Shreyash

**Comment by adrian-bl** [comment]
Could you point me to the repo where you are hosting your changes to vanilla?

**Comment by ShreyashPromact** [comment]
@adrian-bl 
I have not changed anything in your code. I am just mentioning the issue I am facing in the current code. So why is it so?

Sincerely,
Shreyash

**Comment by adrian-bl** [comment]
No, you did make changes.
So there is no point in discussing it here.

**Comment by ShreyashPromact** [comment]
@adrian-bl 
If you found that I have made changes then share that branch reference here so I can verify it.

I have not updated your repo then How you can blame like this?

**Comment by adrian-bl** [comment]
I asked you to share YOUR branch.
I never said that you changed my repo (which wouldnt be possible)

**Comment by ShreyashPromact** [comment]
@adrian-bl 
But at least tell me why I am getting this message? What is the problem? Public repository means anyone can change the code anytime for their own use. You have to give the explanation why is it so? 

Sincerely,
Shreyash

**Comment by Adonai** [comment]
@ShreyashPromact, you got it wrong. This code is licensed under GNU GPL, which means you must share the source code of your modifications to your users.

While @adrian-bl is not your user, you may not share your code with us. But we can't know what's wrong with your code without looking at it, that's why it's highly recommended.

As for the message you get, I don't see a problem in it. You cloned the repo, you installed the apk, so it's relatively easy for you to debug all Toast.makeText messages to see where this particular popup shows up.
