### ISSUE TITLE
Cannot queue a directory with files that Android did not index yet.

### ISSUE THREAD

**Issue by sluchacz** [vanilla-music/vanilla#485]
When trying to queue a whole directory of fresh files, files are playable and queable individually, but trying to enqueue whole directory results in "0 tracks enqueued". After forcing Android media indexer to process fresh files, directory enqueing seems working. 
Dealing with Android media indexer is a hassle, since program can read and play files in the directory as files, why not enqueue them as files, no matter if Android knows about them as media?

**Comment by adrian-bl** [comment]
> why not enqueue them as files, no matter if Android knows about them as media?

Because this would require us to index the files on-the-go which would cause an inacceptable slow down:

As an example: If you try to enqueue /sdcard:

* With the current approach, we can query the media library for /sdcard/%

* With the proposed solution, we would have to index EVERY file on-the-fly as we don't know if there are any missing files. Doing this would take multiple minutes and is not acceptable.

**Comment by adrian-bl** [comment]
closing this as wontfix

**Comment by kasim1r** [comment]
Hi,
I'm not posting to reopen this issue, but because I'm interested - I have the same feelings as the opener.

You state that 
> Because this would require us to index the files on-the-go

What I don't understand here is why everything needs to be indexed. Years ago, I came to this player because of the "play files as they are" feature. Did that go away or was indexing quicker back then? I always had the impression that when I use the "files" tab (it's the only one I use, I disabled all others), Vanilla would do it's own thing... Can you give me a heads up, please?

**Comment by adrian-bl** [comment]
> What I don't understand here is why everything needs to be indexed. 

Because we need certain information to enqueue the song, such as a title and (most importantly and the most expensive thing to get!) the duration.

> Years ago, I came to this player because of the "play files as they are" feature. Did that go away or 
> was indexing quicker back then?

This function didn't change since years: Having songs indexed was a requirement since forever.
Did you change your phone (firmware?) in the meantime? Maybe the old version of Android was just quicker at indexing things.

**Comment by andiandi13** [comment]
> Years ago, I came to this player because of the "play files as they are" feature. Did that go away or
was indexing quicker back then?

I think he refers to pre-1.0.47 versions were it was using android's media database so each and every file of the filesystem was indexed right from the beginning. If so he just have to index Sdcard0 + Sdcard1 and it'll be the same.

**Comment by adrian-bl** [comment]
We get notified about changes to androids internal media library and therefore should pick up changes instantly. At least on my phone, this seems to work well.

**Comment by kasim1r** [comment]
Thanks guys for the explanations.
How can I make my Android do "instant" indexing of my SD card - because that's obviously the reason why Vanilla sometimes doens't enqueue folders...? Can't seem to find an option for that in the settings.

**Comment by andiandi13** [comment]
@kasim1r Including folders in the scanner isn't only for manual scan but also for automatic scan.

So if your Music folder is included, as soon as you copy a song into it, it should appear in Vanilla (actually if android's media library detect an update, like a copy, a download, then Vanilla update its own library thanks to that information) as Adrian said.

It works for me if I copy a song, move it or download it.

**Comment by kasim1r** [comment]
Thanks again, that's cool.
