### ISSUE TITLE
Disappearing Albums

### ISSUE THREAD

**Issue by Allanitomwesh** [vanilla-music/vanilla#526]
When you go to the album list and select an album to view the track list, if you press the back button, YOU GO BACK TO AN ALBUM LIST OF ONE. The others vanish.

**Comment by adrian-bl** [comment]
Could you post a screenshot from before & after?

I think what happens is that tapping on an Album changes the Artist to the internal 'primary artist', so the limiter (visible on the left bottom corner) changes from

> Artist1

to

> Artist2 > Album

So hitting back will go to the albums of 'Artist2' instead of 'Artist1' (But swiping left would bring you back to Artist1)

**Comment by Allanitomwesh** [comment]
Hmmn, closing the limiter (never noticed that thing, you should make it bigger) with the wee little X brings back the full list of albums

**Comment by jooola** [comment]
Not sure but this may be the same problem here #527

**Comment by adrian-bl** [comment]
No: this is 'just' a confusing UI cornercase / issue
