### ISSUE TITLE
Changing tab order change the activated tabs

### ISSUE THREAD

**Issue by Theobald93** [vanilla-music/vanilla#543]
Hey,
if i change the Tab order the activation-marks stay on the same position and so if you save the new order the activated Tabs are wrong.
For example:
Genres are on the last postion, it is the only Tab i activate.
Save.
I order Genres to the first position.
Save.
Now Genre is at the first position but the activation-mark stays at the last position. Now at the tab "Playlists". "Playlists" is the only active tab.

Android 5.1.1
Vanilla Music 1.0.48 Jan 30 2017 via F-Droid

**Comment by adrian-bl** [comment]
That's not a bug: Changing the tabs may actually have the current one vanish - there is just no point in trying to 'follow' the tab as this is sometimes not possible. (And this is a non-issue anyway.)

**Comment by SebiderSushi** [comment]
Hello there, just stumbled over this issue again after changing the tab order myself in a while.
I think that this is in fact a bug and suspect that the issue description might have been misunderstood to have something to do with the "currently active" tab, which is not the case. I suspect such a misunderstanding because the comment about "following" a tab or the concept of a vanishing tab don't make sence in the actual context of the bug.

The issue is only about the fact that the Checkboxes on the "Tab order" settings screen seem to be associated with an index instead of their corresponding tab name as represented in the UI.  
As a result, reordering the tabs on the "Tab order" screen causes Tab names to be detached from their activation state.

From a users perspective this means that changing the tab order requires two steps. First changing the order, followed by reapplying the tab activation as desired. This is not expected behavior, instead, reordering the tabs should intuitively be possible in one go. I can't think of any technical reason for the current behavior.
