### ISSUE TITLE
Feature Request: "Audiobook" support

### ISSUE THREAD

**Issue by bgadwell** [vanilla-music/vanilla#558]
I often listen to audio books on my phone which most often consist of long files. A feature that I have longed for is to have some specific support for these. Far too often, for multiple reasons, I have found myself wasting time and generating frustration trying to determine where I was in this long track.

What I envision is the ability to mark a track or folder as an audiobook completely independent of any genre tag.
An audiobook track would never be considered eligible for inclusion in a shuffle playback
An audiobook track would have the ability to set a bookmark to be stored and retrieved
Playback of an audiobook track would automatically start at the bookmark location if one was present
Anytime an attempt is made to navigate away from or stop playback of an audiobook track a bookmark would automatically be stored for the current playback position

I am not at all familiar with the vanilla codebase, but am a developer by trade and would be very interested in working on this.
Curious if there would be any interest for including this functionality if a pull request was offered.

**Comment by adrian-bl** [comment]
>  An audiobook track would never be considered eligible for inclusion in a shuffle playback

Having an option to exclude tracks from the library/shuffle would be very nice to have (see also https://github.com/vanilla-music/vanilla/issues/530)

> Curious if there would be any interest for including this functionality if a pull request was offered.

Depends on how much code and UI changes such a change would require.
Vanilla Music is first and foremost a music player - that's the one thing it should do well.

**Comment by bgadwell** [comment]
I would imagine an additional menu item on a long press for both tracks as folders
Mark as Audiobook which would toggle to Unmark as Audiobook if selected

I would also imagine one more menu item that would only appear for an audiobook track
Set Bookmark which would toggle to Clear Bookmark if one existed.

Much more could be done if there was a desire to support multiple bookmarks and manage them, but I see that as feature creep at this point.

I do not believe the code to accomplish what I mentioned would be a huge amount, but I first need to get familiar with the codebase to really make an assessment.

It does beg a bigger question of how this would fit into a general feature of excluding tracks from shuffle play which I have described as a implicit attribute of an audiobook (the bookmark feature is more important for my use case). If the logic is there to support exclusion then it really just becomes a UI consideration of how to expose it.

Thanks for the response and the project!

**Comment by yaymeh** [comment]
Audio-book and music playback are very different scenarios with different requirements and problems. What's a feature for one can be an anti-feature, clutter and source of unnecessary complications / bugs for the other. I'd suggest using the music player to play music and an audio-book player (like p.E. "material audiobook player") to play audio books... and wouldn't recommend trying to turn one into even a rudimentary replacement for the other. 

Also simply putting a ".nomedia" file into your audio-book directory might be the best solution for your other problem (many file managers even have a special function to create an empty file with that name). You probably don't want those audio books in the media library at all / in any music players and you might not want book cover images between your photos etc - so that's exactly what ".nomedia" is for. Audio book players usually use directory structure rather than the stock media library anyway.

**Comment by adrian-bl** [comment]
closing this - i don't see me implementing any audiobook related features in the near future.
