### ISSUE TITLE
More descriptive labels and description in Settings interface

### ISSUE THREAD

**Issue by PanderMusubi** [vanilla-music/vanilla#595]
Some of the labels in the settings part of the app are not that clear in explaining what they do. Please add more descriptive labels or descriptions. Also some minor style typos below fix.

* Description under **Settings / Cover art / Load artwork from Android** it says "Query Androids internal media database for album artwork". As a normal user, I have no idea what Androids (→ Android's) internal media database is and what the implications are. Perhaps better to say: "Use artwork extracted by Android from media file metadata such as ID tags" when it indeed implies that only this is happening.
* Text in **Settings / About**, do not use bold except for the headings. Use full urls everywhere, now some are abbreviated or replaced with the word "show". In this way, a user can copy the url without opening it in a browser. Remove also the square brackets. Use also a list under Licenses and in the top section.
* Under **Settings / Media library** the descriptions are missing.
  * "Group albums by folder" When is this useful? If you have albums with various artits but not album artist set in the ID3 tags I expect. Please inform the use of possible reason.
  * "Always use built-in tag reader" Does this relate to the Android stock tag reader or the Vanilla Music tag reader? What does always imply when checked and unchecked? If uncheck, is it used only sometimes? (This is inplied by the work Always.)
  * "Scan full filesystem (Slow)" Do not use capital in Slow → slow. Does it scan my full system or only scan the paths I have added to indexed directories. This is not clear to me.
  * "Flush media database (Dangerzone!)" Why is this dangerous? What are the implications and risks? If it is dangerous, I would not want to have this option or use it. I don't want dangerous software. ;-)
  * "Play time (Hours)" do not use capital in Hours → hours.

I hope we can discuss solutions here first. Willing to provide a pull request.

**Comment by andiandi13** [comment]
I agree, some options are obscure especially in Media Library.

In was thinking a couple days ago of making an FAQ (in-app or on the website, but it would be better not to depend on a internet access) for those labels that sometimes can't be explained well in few words...

**Comment by adrian-bl** [comment]
Having a help page would be great, we could host it at vanillamusic.io (https://github.com/vanilla-music/vanilla-music.github.io - built using Hugo).

Adding a 'help' link to the app wouldnt require any additional permissions.

**Comment by andiandi13** [comment]
And maybe we can (also) add an internal menu, like in Black Player, please take a look :

https://youtu.be/Q6gd8AoHRS0

It's simple, like in html with anchors. (It would be cool to make it the same way as the changelog, with a "show/hide" button)

Or do you want it only on the website ?

**Comment by andiandi13** [comment]
@adrian-bl Could you please answer his questions for these 3 functions so that I can explain that well in the Wiki ?


> "Always use built-in tag reader" Does this relate to the Android stock tag reader or the Vanilla Music tag reader? What does always imply when checked and unchecked? If uncheck, is it used only sometimes? (This is inplied by the work Always.)
> "Scan full filesystem (Slow)" Do not use capital in Slow → slow. Does it scan my full system or only scan the paths I have added to indexed directories. This is not clear to me.
> "Flush media database (Dangerzone!)" Why is this dangerous? What are the implications and risks? If it is dangerous, I would not want to have this option or use it. I don't want dangerous software.

**Comment by adrian-bl** [comment]
# Always use built-in tag reader

Vanilla Musics builtin tag-reader supports Ogg, Opus, Flac, MP3 and MP4 files.
By default, we only use our own tag-reader for Ogg, Opus and FLAC, as i do not consider the other tag readers to be stable enough. However: Enabling this option will cause Vanilla Music to use the internal tag reader (instead of androids own tag reader) for any supported format.

Ergo:
Default: vanillas-builtin-tag-reader(ogg, opus, flac), androids-tag-reader(mp3, mp4, *);
Option enabled: vanillas-builtin-tag-reader(ogg, opus, flac, mp3, mp4), androids-tag-reader(*);

# Scan full filesystem
Thanks: Replaced 'Slow' with 'slower' in 710b284193c9faec8f68c905b4ab09a54157073e
The option still only scans the whitelisted paths, but it checks each and every file it finds.
By default, we only check files which are already included in androids media database. Maybe we should give the option a better description..

# Flush media database
I removed the 'Dangerzone!' as it isn't *really* dangerous:
The option will drop all entries from the database before starting a scan - the only dangerous thing about it is that killing Vanilla Music during the scan would wipe some playlists - but forcefully killing apps is never a good idea anyway :-)

**Comment by andiandi13** [comment]
@adrian-bl 
> By default, we only check files which are already included in androids media database.

But I thought that android media database update itself as soon as there is new songs copied to the device, isn't it the case ?

**Comment by adrian-bl** [comment]
This is usually the case, but Android sometimes fails to pick up new files (or will never pick them up, such as Opus files on Android 6.x), that's why there is an option to also check for unindexed files.

**Comment by andiandi13** [comment]
Alright that make sense, thanks.

**Comment by andiandi13** [comment]
When I uncheck the built-in tag reader box and rescan, I have 5 albums where every songs has no album tag nor artist tag and even title (its the filename instead).
In literally any player on my phone the tags are OK (id3v1 + id3v2) , even in the tag editor plugin ! :O

Do you have any idea about the origin of such an issue since you said its "Android" tag reader ?

**Comment by andiandi13** [comment]
Example : https://preview.ibb.co/bVhz75/28367.jpg

**Comment by kirbyfan64** [comment]
FWIW the tag editor uses a completely different tagging library than Vanilla *or* Android.

**Comment by adrian-bl** [comment]
Hmm.. it would be strange if the results of the android tag reader are worse in Vanilla Music than in other apps (which other music player did you try?)

**Comment by andiandi13** [comment]
I tried Samsung stock player, Black player, AIMP, Mixplorer internal audio player, Music Tagger (a tagging app) etc..

**Comment by adrian-bl** [comment]
Black Player and AIMP do (AFAIK) not use Androids tag reader - not sure about the samsung player.

But feel free to send me a sample to adrian@blinkenlights.ch

**Comment by andiandi13** [comment]
I would love to send you a sample, its so strange.

Oh and I tried Vanilla 1.0.46 (before it had it's own library)

**Comment by andiandi13** [comment]
File sent :)

**Comment by PanderMusubi** [comment]
@adrian-bl Thanks for the explanation. When you use only MP3, what are differences between Android 7.1 tag reader and the Vanilla Music built-in tag reader? Which support ID3v2.3? Which supports ID3v2.4?

**Comment by andiandi13** [comment]
@adrian-bl I think I figured it out, look at the tags, there are in ID3v1+ID3v2.4.
I read you says on an issue that Vanilla don't support v2.4.

But don't you say its android's tag reader, or maybe Vanilla TAKES the informations from android and "copy paste" them in the player, merge them, whatever, and fails to read it correctly ?

**Comment by adrian-bl** [comment]
@PanderMusubi Androids builtin tag reader supports whatever the vendor of your phone firmware chooses to implement. Vanillas builtin reader should be OK with ID3v1 and ID3v2.3 and 2.4 - however: I wouldn't consider Vanillas builtin MP3 tag reader to be stable, that's why it is disabled by default.

@andiandi13 It should be able to handle 2.4, can you link to the issue?
Also: I had a look at your file, and it has both ID3v1 and ID3v2.4 tags:

```
<FILE> 16 kata-tsubasa no tenshi.mp3
DBUG >> tag version ID3v2.4
<duration> = 439
<_hdrlen> = 809687
<ALBUM> = [Final Fantasy VII Original Soundtrack]
<YEAR> = [1997]
<GENRE> = [Soundtrack]
<ARTIST> = [Nobuo Uematsu]
<type> = MP3/ID3v2
<TRACKNUMBER> = [16]
<TITLE> = [One-Winged Angel]
```

Vanillas own tag reader is able to parse the ID3v2.4 tag - but i have no idea why the internal tag reader fails on your phone for this tag :-( - it works on my test device running Android 5.
Maybe there is something special with the ID3v2.4 tag and androids tag reader attempts to parse it (instead of the v1 tag) but then fails somehow...

**Comment by andiandi13** [comment]
@adrian-bl Sorry what do you mean by "link to the issue", I've not created an issue here, or I've not understood :)

But if android fails to read it, somehow, then why it succeed anywhere else (in other players), is it not the import of the tags from Android's library that fails in Vanilla ? Or vanilla imports nothing ? Is it just like a direct "link" to some tags from the system ? 

As far as I'm concerned, I prefer compatibility for everything, so I just convert tags to ID3v2.3 but this issue is odd.

**Comment by andiandi13** [comment]
@adrian-bl I don't think you should bother with that id3v4 its not that serious :-)

However, I have 2 points to raise, which will determine the way I write to the user guide :

**1**- Why does cover art from folder (cover.jpg etc..) prevail over the embedded cover ? The file embedded cover is mostly the true cover while there can be jpg images among the tracks named cover.jpg or artwork.jpg "incidentally" with no link to the cover. And even that's not the case don't you think it make more sense to give preference to the embedded cover ?

**2**- I think the structure of "Volume during notification" + "Keep playing on permanent audio focus loss"  box had to be rethink.
First the fact that Volume during notification option is inside "Audio" menu and not "Notifications" menu can be confusing.

Also, "Keep playing on permanent audio focus loss" box should be in "Audio" menu because its not only valid for notification, but for anything, even if I'm playing a video, I can play the sound too with that.

Just in passing, I wanted that audio focus option in Vanilla for long, and I'm surprised that its already there and I just saw it now, I think its definitely not obvious to find it. Tell me what do you think.

**Comment by adrian-bl** [comment]
> Why does cover art from folder (cover.jpg etc..) prevail over the embedded cover ?

Until Android 7.x, the quality of cover art extracted by Android (that's what we use for embedded covers) was abysmal.

> And even that's not the case don't you think it make more sense to give preference to the embedded 
> cover ?

You can just disable the 'load cover from..' option in the settings: If this is disabled, Vanilla Music will always query Androids media database to load the cover.

> First the fact that Volume during notification option is inside "Audio" menu and not "Notifications" 
> menu can be confusing.

The Notification in this context has nothing to do with notifications *created* by Android.
The option controls how we react if some *other* application plays a notification sound. (by stealing our audio focus)

> Also, "Keep playing on permanent audio focus loss" box should be in "Audio" menu because its not 
> only valid for notification, but for anything, even if I'm playing a video, I can play the sound too with 
> that.

Maybe the wording of the option is suboptimal and we should just rename it to 'behavior during audio focus loss'.

**Comment by andiandi13** [comment]
> The word 'Notification' in this context has nothing to do with notifications created by Vanilla Music.

Yes I mixed the two ^^

> Maybe the wording of the option is suboptimal and we should just rename it to 'behavior during audio focus loss'.

I mean, yes it would be better to rename it, but I still think that that box should be a outside that option (and aside since you keep it in "Audio") because I does not concern only notifications but any audio stream, don't you think ?

**Comment by ecanja** [comment]
@andiandi13
> Example : https://preview.ibb.co/bVhz75/28367.jpg

Stupid question: How did you get to a view where all the metadata tags are shown?

**Comment by adrian-bl** [comment]
Closing this old bug as we now do have a help section
