### ISSUE TITLE
Vanilla says "<No Album>", but other apps show an album

### ISSUE THREAD

**Issue by kirbyfan64** [vanilla-music/vanilla#608]
Example file: https://drive.google.com/file/d/0B3RBF3Zy7CAXdWhiaXdqOG1XLU0/view?usp=drivesdk

Other apps:

![Other apps](https://s5.postimg.org/8bt0blwg7/Screenshot_20170606-124750.png)

Vanilla:

![Vanilla](https://s5.postimg.org/xgk0p0vwn/Screenshot_20170606-124945.png)

Tested with both the builtin and normal tag reader.

**Comment by Adonai** [comment]
didn't know Zeke has its' own theme...

**Comment by kirbyfan64** [comment]
Do you mean the tag editor plugin? It shows the correct album.

(Zeke...oh, is that the name of the beast titan? TBH I know little about the anime; I'm just a huge Sawano fan.)

**Comment by adrian-bl** [comment]
```
[adrian@fuzzy tmp]$ id3info 02.\ APETITAN.mp3 

*** Tag information for 02. APETITAN.mp3
=== TIT2 (Title/songname/content description): APETITAN
=== TPE1 (Lead performer(s)/Soloist(s)): Hiroyuki Sawano
=== TALB (Album/Movie/Show title): "Attack on Titan" Season 2 Original Soundtrack

=== TCON (Content type): Anime
```

Turns out that TALB contains a newline char, which doesn't match our filter for 'anything' 
(https://github.com/vanilla-music/vanilla/blob/a697e2a82748b736053b956e0ce0d765d1916684/src/ch/blinkenlights/android/medialibrary/MediaMetadataExtractor.java#L59)

Commit f980395e3bfbae3df0ff0609ee7c3bc20901d522 changes the regexp, so tags with newlines will be picked up.
