### ISSUE TITLE
Version 1.0.52 - from fresh install unable to scan library and add new music

### ISSUE THREAD

**Issue by Alucinatus** [vanilla-music/vanilla#613]
After having a fresh install of v1.0.52 I am unable to scan my media library. It does however keep my music if i use the previous version and then update the app, but afterwards I cannot make any changes. Tested on Sony Xperia z5, and Samsung Galaxy S8. Also would it be possible to implement an amoled theme?

**Comment by adrian-bl** [comment]
* Did you try a manual scan?
* please provide a logcat

**Comment by yaomtc** [comment]
I have the same issue. Using the latest version from F-Droid on my Nexus 5X with LineageOS. I actually noticed before this that shuffle wasn't doing anything anymore, and it would only play in a linear order. I've since cleared the app data and tried manually scanning, but nothing happens. How do I get the logcat?

**Comment by adrian-bl** [comment]
Install the android utils (or the sdk) and run

adb logcat

while the phone is connected to your computer.

**Comment by adrian-bl** [comment]
Also:

What happens if you start a manual scan in Settings > Media Library?

Does it even start? Or is it hanging?

Does ticking the 'full scan' option make a difference?

**Comment by Alucinatus** [comment]
It seems to just scan the indexed directories as i assume it should, but i cant seem to edit the indexed directories. My music is on the sd card if that helps. I cant do a logcat at the moment sorry.

**Comment by yaomtc** [comment]
[logcat.txt](https://github.com/vanilla-music/vanilla/files/1073416/logcat.txt)

I have it configured to only index `/storage/emulated/0/Music`. When I hit the Start Scan button, nothing appears to happen, and the app does not hang. Checking "Scan full filesystem" doesn't seem to make a difference. Judging by the log, I'm guessing it's unable to create a notification, what with "no com.android.systemui"? I don't know.

**Comment by adrian-bl** [comment]
@Alucinatus You need to long-press on a directory to change the state (As described in the toast message which appears when you open the dialog). Did you try this?

@yaomtc 

```
06-13 23:12:22.648 19613 19634 V VanillaMusic: xxx --- starting scan of type 104
06-13 23:12:22.673 19613 19634 V VanillaMusic: NativeLibraryScanner finished, mtime mark is now at 0
```
So Vanilla Music tried to read androids media database but didn't get a single file.

This either indicates that the database is empty or that we do not have permission to read tracks. (Are you using a custom ROM?)

* Do you see any files in the files tab?
* What happens if you check the 'Full Scan' checkbox?

**Comment by Alucinatus** [comment]
That worked, thanks! All of my music was on my SD card which isn't in the default indexed directories. Once I added it the scan completed.

**Comment by adrian-bl** [comment]
Whats the path of your sd card? We are supposed to autodiscover it.

**Comment by Alucinatus** [comment]
"0123-4567"

**Comment by Adonai** [comment]
That's SAF-managed SD-card, I guess, not internal one.
@Alucinatus , it's removable, right?

**Comment by yaomtc** [comment]
@adrian-bl I guess LineageOS would be a custom ROM, yeah. I do see files and folders. If I go into the Music folder and navigate to some music files, they'll play just fine.

> Checking "Scan full filesystem" doesn't seem to make a difference.

**Comment by Alucinatus** [comment]
@Adonai Yes it's removable.

**Comment by yaomtc** [comment]
Oh. It was the .nomedia file in my Music folder, put there to stop Gallery from including all the album art in there. I guess that does the same for Vanilla Music. My mistake. Flushed the database and did a full scan, and it's scanning now.

**Comment by adrian-bl** [comment]
@yaomtc ok, then this was WAI :-)

@Alucinatus Oh: Seems like we really do not pick up these sd-card names:
We used to 'guess' /stoarge/sdcard1, but this isn't true anymore for most devices since Android 6.x.

Commit 7612febbabcad3466dda814ef55f8c3963d4871e should hopefully fix this, at least it works on my two test devices (AOSP 5.0 and LineageOS)
