### ISSUE TITLE
Possibly broken track reporting on Android 7.x

### ISSUE THREAD

**Issue by Like-all** [vanilla-music/vanilla#630]
- Vanilla Music Version (Settings -> About): 1.0.53
- Android Version: 7.1.2 (Lineage OS 14.1)
- Phone vendor / model: Moto G 2015(osprey)
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description

Yesterday I reflashed my Moto to Lineage OS 14.1 and then got scrobbling to Last.FM broken. Neither official app works, nor SLS. After observing it via logcat I've found out that emitting events to the API is broken(reporting null track values). On Android 5.x it was working well.

## Steps to reproduce the issue

- Flash Android 7.x
- Install Vanilla Music
- Enable "standard behaviour" checkbox in settings
- Install Simple Last.fm Scrobbler
- Enable ADB
- Open Logcat
- Start listening to music
- See "Got a bad track" message

## Screenshot / Video (If applicable)

![2017-07-03 08-21-38](https://user-images.githubusercontent.com/674257/27784698-4b617e74-5fdb-11e7-973f-6d7040277ed6.PNG)

**Comment by adrian-bl** [comment]
Did you try to enable 'Emulate stock broadcasts' ? I assume this was enabled before, so this is why it worked:

What you see there is actually a bug in SLS, which was fixed by them in https://github.com/tgwizard/sls/commit/87136dca27208f1cb5150398e842be6515ed78e5 but (not yet) released.

Technical background:

SLS expects an Integer - but we are sending a Long value:
https://github.com/vanilla-music/vanilla/blob/753410bbefb79e2f49b0de00ffa1ab4459e9707c/src/ch/blinkenlights/android/vanilla/PlaybackService.java#L1125

The documentation clearly states that _ID columns are 'Long' and not 'Int' (https://developer.android.com/reference/android/provider/MediaStore.Audio.AudioColumns.html)

**Comment by Like-all** [comment]
Thank you for feedback! Stock broadcasts were enabled, that's why I got confused. Will look forward for updates from SLS.

**Comment by Like-all** [comment]
Very unhappy to see that, but it seems like the development of both scrobbling apps is being stalled :(

**Comment by Like-all** [comment]
I'm closing this, because the problem is not on your side, but would like to know more technical details about broadcasts emission and how to subscribe to them from command line. I haven't gotten enough experience in writing applications for Android, so the only possible solution is to write either a daemon in golang, or even a bash script to work around the problem until SLS gets fixed.
