### ISSUE TITLE
[SUGGESTION] Add a 'Scroll to playing track' button

### ISSUE THREAD

**Issue by andiandi13** [vanilla-music/vanilla#798]
Vanilla Music Version : 1.0.62
- Android Version: 4.4.4
- Phone vendor / model: Galaxy S5
- Application was downloaded from :
  - [X] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [X] No
  - [ ] NA / Don't know.

## Description

The current scroll to track function is very useful to not lose focus of the playing song and the tracks surrounding it.

However we may scroll into the library and lose the track location's.

So I thought about an option located inside the three dot menu on the queue (next to the search button, below sorting).

Many times, I had to use the search to find the playing song.

That option would be welcomed.

**Comment by minus7** [comment]
I'd like that as well, or maybe even with automatic scrolling on song change and when activating the queue view.
I tried myself at the button but ended up quite getting nowhere after about 2 hours of digging through the code. `ShowQueueFragment` has the queue and already has code for focussing the current track; `SlidingPlaybackActivity` has the menu you want the entry in. Unfortunately, there is no direct way to talk to the queue from the menu, since it's only every modified through `TimelineCallback`.

Actually, focussing the new track on song change is easy (in fact it's explicitly not done currently). Just change to `true` [here](https://github.com/vanilla-music/vanilla/blob/5ff7f8eddb16e4c15546584b7af3e8b931aa2a21/app/src/main/java/ch/blinkenlights/android/vanilla/ShowQueueFragment.java#L240). Should optimally be a setting I guess.

**Comment by andiandi13** [comment]
You're right, automatic scrolling inside the queue would be useful too !

**Comment by andiandi13** [comment]
@adrian-bl  : little issue with the new _scroll to track inside queue_ feature : if you reorder only one song with the six dots, it wrap to the playing song so you _can't_ sort the queue as you wan.

I guess it's because a sorting of the queue equal an update of the queue equal scrolling.

Maybe you can find a workaround on the code...

**Comment by adrian-bl** [comment]
Oh yeah, thanks for the feedback: it behaves indeed pretty horrible.

I pushed
https://github.com/vanilla-music/vanilla/commit/480df8e99a441590c7b2c02f1ca79716863e4d58

which moves the scroll code to the setSong() callback (which only gets called if the currently playing song changes) - this should hopefully work better.

**Comment by andiandi13** [comment]
@adrian-bl It work great now. Thanks !
