### ISSUE TITLE
Files tab now always says 0 tracks playing, rescan doesn't help

### ISSUE THREAD

**Issue by killerkalamari** [vanilla-music/vanilla#809]
- Vanilla Music Version (Settings -> About): 1.0.70 (dated 8/15/2018, that's about when this problem started, although I did add songs yesterday as well)
- Android Version: 8.0.0
- Phone vendor / model: Asus Zenfone 4
- Application was downloaded from (use `[x]`):
  - [x] Play Store
  - [ ] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [x] Yes
  - [ ] No
  - [ ] NA / Don't know.

## Description
"Play all" now always results in "0 tracks playing" toast. This used to let me play the files. I tried rescanning my library and even dumping and scanning. No luck.

## Steps to reproduce the issue
1) Go to Files tab
2) Press Play all

## Other thoughts
I only ever use the Files tab because I just don't want to tag all my files. The constant manual scanning to get "Files" working every time I add files is getting pretty old, but the app is great, so I put up with it. This is the first time the scan didn't work. 

I've done some Android development, but haven't investigated the Vanilla Music codebase. If I forked Vanilla Music could I actually play tracks without a Media Library, or is that some Android requirement for playing songs? 

I'd love to strip out all the stuff I don't use, and also add controls to fast forward and rewind for audio books.

**Comment by andiandi13** [comment]
Be sure that those tracks are indexed

https://github.com/vanilla-music/vanilla-music.github.io/wiki/FAQ#media-library-media-scanner-missing-tracks

**Comment by MarcNumerique** [comment]
I am reporting the exact same issue, as described. The issue also appeared on the version released on August 15, 2018. Before that, it worked fine.
I will add that my media library is located on an sd card. It is scanned. It was rescanned, with success. The location of the library is included in the media librairies, with a check mark on the left. The Android phone was rebooted. Also, although the "Play all" function doesn't work, it is worth noting that clicking on an individual media will play it. All the files in the directory can thus be played individually, just not all of them in sequence by using "Play all".

**Comment by andiandi13** [comment]
@MarcNumerique Est-ce que tes fichiers sont bien taggués ? Regarde mon lien c'est le wiki avec une FAQ.

Si tu as des fichiers sans tag (ID3...), ils peuvent ne pas êtres reconnus.

S'ils ont que des tags ID3v1 met leur des ID3v2 aussi.

**Comment by MarcNumerique** [comment]
Mes fichiers ont le tag ID3v2.2. Ils sont détectés par Vanilla Music et ajoutés dans la librairie.
--
Since the question has been raised, I'm adding that the files are tagged with ID3v2.2. They are all detected by Vanilla Music, added to the multimedia . They were ripped from personal CDs of classical music.
Also, when I use the other tabs, I can listen to a complete selection by artist, genre, etc. Only in the File tab is the "Play all" option not working.

**Comment by MarcNumerique** [comment]
Mes fichiers ont le tag ID3v2.2. Ils sont détectés par Vanilla Music et ajoutés dans la librairie.

Since the question has been raised, I'm adding that the files are tagged with ID3v2.2. They are all detected by Vanilla Music, added to the multimedia . They were ripped from personal CDs of classical music.
Also, when I use the other tabs, I can listen to a complete selection by artist, genre, etc. Only in the File tab is the "Play all" option not working.

**Comment by andiandi13** [comment]
Effectivement ça me fait la même chose.

@adrian-bl the Play all function seems to be broken in file tab for every files (litteraly all my library).

**Comment by adrian-bl** [comment]
Indeed.

Guess i broke it in 6992342f1550c482dbff0a3b7088ab391e5b3d22

**Comment by MarcNumerique** [comment]
A bug fixed is a bug forgotten. ;o)

**Comment by adrian-bl** [comment]
Closing this:

* 1.0.71 is tagged, so f-droid should start builds soon
* I uploaded 1.0.71 to the beta channel on the play store, will promote to 'live' tomorrow.

**Comment by killerkalamari** [comment]
Thank you for the quick fix! Working fine now (1.0.71).

**Comment by rafiberlin** [comment]
Hi, I still experience the issue with 1.0.71. Do you have to do anything special to make it work? I deinstalled and re-scanned the library many times but it did not help. Device: huawei mate 10 pro, android 8.0. Thanks for your help!

**Comment by MarcNumerique** [comment]
1.0.71 corrected the bug for me. Device is LG-M703 with Android 7.1.1.

**Comment by andiandi13** [comment]
Works for me too. Galaxy S5 4.4.4

**Comment by rafiberlin** [comment]
Thanks for the quick feedback. how big are your libraries? i gave near to 9000 tracks. could it be an issue?

**Comment by andiandi13** [comment]
2000+ tracks.

But I don't think tracks number are an issue though.

Try Vanilla Nightly, maybe there is still junk files in stable version.

**Comment by adrian-bl** [comment]
* Are you sure that the files are indexed? Did you try a 'full scan'?

* Is the directory path the indexed one or a symlink? (/storage/emulated != /sdcard)

**Comment by andiandi13** [comment]
@rafiberlin @adrian-bl I experienced the issue when I removed my SDCard from the phone, even when I put it back and my tracks are reloaded into the library, Files tab says 0 tracks playing.

# What I've done since I'm root, is that I went to **/data/data/ ch.blinkenlights.android.vanilla/databases** and I deleted all the files and then rescan my library.

So @adrian-bl  maybe there is an issue that appears in conditions similar to SDCard removal ...

@rafiberlin If you are root try to do the same thing.
