### ISSUE TITLE
Add ability to seek back and forth within a track

### ISSUE THREAD

**Issue by dandv** [vanilla-music/vanilla#81]
This would be the most important step towards adding audiobook features (#56).

In a long audio track, using the seekbar is very imprecise, especially while driving. Meridian Player lets you swipe left or right to seek backward or forward by 10 seconds - highly useful.

Would be a great action for swipe up/down in Vanilla.

**Comment by adrian-bl** [comment]
Targeting this for 1.0.2:

We can add a new swipe action and also have it as a long-press action in the FullPlaybackActivity.

**Comment by adrian-bl** [comment]
Fixed in 4a534ce2e252b6d28d12f75235c70b877076719e

**Comment by un-logic** [comment]
Long press doesn't work for me meanwhile swipes are fine, running at 1.0.30.
Also is it possible that seeking trough track with Bluetooth headset via AVRCP will work too after long press bug got fixed? Other players can seek via AVRCP with this headset.
Anyways, keep up the good job and thanks in advance!

**Comment by adrian-bl** [comment]
Long presses work for me - make sure to exit the full-playback activity after changing the setting (yes, that's buggy - the full playback view doesn't have a settings-change listener and will not realize the change until it has been re-created)

AVRCP is a different issue: We are probably just not handling the keycode, but i do not have the hardware to test it.

You could have a look at MediaButtonReceiver.java:processKey() and try to dump out the key code for long-presses (if there are any?)

**Comment by un-logic** [comment]
Now I've got it. When you said "long-press action" you meant action triggered by press on cover, which is working great by the way, whilst I thought of long pressing on rewind and fast forward buttons.  So, please, excuse me for this mess.
You are right about AVRCP,  now it's clear that it's completely different issue. You see, due to method of rewind/fast forward implemented in SBH50 Bluetooth headset, by long-pressing and holding previous/next track buttons, I got it confused with this issue. I pursued following logic:
1. Samsung Music app is capable of seeking within a track by long-pressing previous/next track buttons of UI whilst Vanilla isn't.
2. Rewind/fast forward via AVRCP works fine with Samsung Music app whilst that is not the case with Vanilla.
3. Conclusion is that seeking within a track via AVRCP implemented this way: pressing down previous/next track button of headset triggers sending key down event, app is listening for key down event and starts up internal timer, if it counts down and there is no key release event being sent by headset, then it starts to rewind/fast forward a track until key release or any other key down event is caught.
4. I saw and misunderstood your first answer to this issue the way I've described previously but nothing is working. That's why I suggested that these two issues are related. Now it's clear that there should be opened another issue considering AVRCP.
As for different key codes for rewind/fast forward I am not sure if you addressed to me but is there any user friendly app listing key codes and events, because I'm not a programmer?
P.S.: Sorry for lot of words.

**Comment by un-logic** [comment]
I've made a little research and got this link 
http://grepcode.com/file/repository.grepcode.com/java/ext/com.google.android/android/4.2_r1/android/view/KeyEvent.java
which, in particular said the following:

Key code constant: Play/Pause media key.
278 
279     public static final int KEYCODE_MEDIA_PLAY_PAUSE= 85;
    
Key code constant: Stop media key.
280 
281     public static final int KEYCODE_MEDIA_STOP      = 86;
    
Key code constant: Play Next media key.
282 
283     public static final int KEYCODE_MEDIA_NEXT      = 87;
    
Key code constant: Play Previous media key.
284 
285     public static final int KEYCODE_MEDIA_PREVIOUS  = 88;
    
Key code constant: Rewind media key.
286 
287     public static final int KEYCODE_MEDIA_REWIND    = 89;
    
Key code constant: Fast Forward media key.
288 
289     public static final int KEYCODE_MEDIA_FAST_FORWARD = 90;
    
Key code constant: Mute key. Mutes the microphone, unlike KEYCODE_VOLUME_MUTE.
291 
292     public static final int KEYCODE_MUTE            = 91;

Not sure if it's related or any help though.

**Comment by adrian-bl** [comment]
The keycodes are well known (also documented in the SDK docs).
What i would need is to know *which* keycode the bluetooth device sends... and if it sends it once or if the keycode is repeated.

@un-logic I suppose that you own an AVRCP device?
If yes, then you could add some logging in MediaButtonReceiver.java:processKey() and send me the output. This should be enough to figure out the keycode(s) sent by the device.
