### ISSUE TITLE
Tap on cover to show Lyrics

### ISSUE THREAD

**Issue by maverick74** [vanilla-music/vanilla#893]
Would be nice to be able to set an option that when one Taps on the album cover (in the main app) it would show the song's lyrics

**Comment by adrian-bl** [comment]
The next release will have a shortcut to access the plugins in the actionbar (see screenshot below).

This will give quick access to the lyrics plugin.
Having this as a cover-tap action doesn't seem to be a good idea to me UI wise and 
 would greatly complicate the current cover-tap action code (user would need to be able to select a specific plugin / what happens if the plugin got uninstalled but the action is set to this plugin, etc...)

![image](https://user-images.githubusercontent.com/568734/50791432-1feb9900-12c2-11e9-9548-7683f13b9cd5.png)
