### ISSUE TITLE
CP1251 support

### ISSUE THREAD

**Issue by MVoloshin** [vanilla-music/vanilla#922]
Hello, I ve noticed that latest Vanilla Music version does not display most of Russian tags correctly (because they have CP1251 encoding). I know that it does not match official ID3 standards, but stock music player displays such tags as usual.

**Comment by adrian-bl** [comment]
Can you send me a sample file to adrian@blinkenlights.ch?

You could also try to untick the 'Always use built-in tag reader' option in Settings > Media Library

**Comment by MVoloshin** [comment]
Done. Did you get the files?

**Comment by adrian-bl** [comment]
yes, thanks: i will try to have a look on friday.

But did you try the built-in tagreader method i mentioned?

**Comment by MVoloshin** [comment]
Yes, this method partially solves the problem. Is it possible to set this parameter disabled by default?

**Comment by adrian-bl** [comment]
Ok, so i had a look at the files and they simply have an invalid encoding:

For example: 01.mp3 and 02.mp3 both claim to use ISO-8859-1 as encoding: which we respect and therefore use and causes us to return gibberish as the encoding in the file was wrong.
03.mp3 however claims to use UTF16 which results in correct decoding:

```
<ARTIST> = [Браво]
<ALBUM> = [zvukoff.ru]
<GENRE> = [Unknown]
<TITLE> = [Этот город]
```

So there is not much we can do: The files simply contain invalid encoding information.

The reason why *not* using the internal tagreader seems to make things better is because android sometimes guesses the charset. In this case, it seems to get it right, but in most cases it gets it horribly wrong, so that's why we are not using it by default.
