### ISSUE TITLE
Some .opus tracks are missing

### ISSUE THREAD

**Issue by recod4** [vanilla-music/vanilla#932]
Vanilla Music Version (Settings -> About): 1.0.82
- Android Version: 9.0
- Phone vendor / model: Xiaomi
- Application was downloaded from (use `[x]`):
  - [ ] Play Store
  - [x] F-Droid
  - [ ] Other (Nightly Build)
- Did this work in a previous version?
  - [ ] Yes
  - [x] No
  - [ ] NA / Don't know.

## Description

There are some tracks in my music library that are not picked up during scan (both normal and full scan). I got about 80% of my opus library after scan, the rest is not there. Also if I try to manually play them via files category, it plays the first song from the folder instead of the one "missing". 

## Steps to reproduce the issue

...

## Screenshot / Video (If applicable)

...

**Comment by Adonai** [comment]
@recod4 you should probably send sample file to adrian@blinkenlights.ch

@adrian-bl there are cases where OpusTags comment spans multiple pages, especially when it contains heavy embedded pic, does bastp know it?

**Comment by recod4** [comment]
Yeah I just noticed that every missing song has front cover that's over 2 MB in size. I sent a sample too.

**Comment by adrian-bl** [comment]
Thanks for the sample.

Bastp can parse the file just fine, the issue seems to be that the native metadata extractor is not able to detect it as an audio file and fails to report a duration:

https://github.com/vanilla-music/vanilla/blob/master/app/src/main/java/ch/blinkenlights/android/medialibrary/MediaMetadataExtractor.java#L316

All three extraction calls return NULL, so we return early and consider the file to not be playable.

Commenting this out and supplying a fake duration causes the file to be played back.

Not sure what to do here: We could theoretically fall back to bastp's duration calculation (which is not very exact) - but then if the operating system reports that it does not recognize a file as an audio file, we kind of should just be able to believe that....

**Comment by Adonai** [comment]
Sounds like new advanced config option in media library preferences :)

**Comment by adrian-bl** [comment]
I tried to re-mux the file using ffmpeg and opusenc: It seems that the size of the cover is indeed an issue for android: Playing the file still fails with an 1.2MB cover, but starts to work once i resized it to about 400KB.

I don't think there is anything we can/should do: If the OS barfs at parsing the file, it seems to be reasonable to assume that it would also fail to actually play the contents of it.

So unfortunately, the solution here is to remux the file using a smaller cover.
(I might give exo-player a second try at some time, which will decouple us from OS bugs and give us a way to solve such issues)
